In [1]:
import pandas as pd
import torchtext
from torchtext.vocab import Vectors
from torchtext.legacy import data
import torch
from torch import nn
import torch.nn.functional as F
from d2l import torch as d2l
from torch.autograd import Variable
from sklearn import metrics
import sys
sys.path.append("D:/Experiment")
from tqdm import tqdm
from MyKu import training
from MyKu import processing
from torchtext.vocab import Vectors
from spacy.lang.en import English

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(DEVICE)

cuda:0


In [2]:
def global_max_pooling(tensor, dim, topk):
    """Global max pooling"""
    ret, _ = torch.topk(tensor, topk, dim)
    return ret

class textCNN_LSTM(nn.Module):
    def __init__(self, vocab_size, embed_size, num_hidden, num_layers, dropout, **kwargs):
        super(textCNN_LSTM, self).__init__(**kwargs)
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.dropout = nn.Dropout(dropout)
        self.decoder = nn.Linear(num_hidden * 2, 2)
        self.conv2 = nn.Conv1d(embed_size, 100, 2, padding=1)
        self.conv3 = nn.Conv1d(embed_size, 100, 3, padding=2)
        self.maxpool1D = nn.MaxPool1d(4, stride=4)
        self.seq_model = nn.LSTM(100, num_hidden, bidirectional=True, num_layers=num_layers, batch_first=True, dropout=dropout)
        self.relu = nn.ReLU()

    def forward(self, inputs):
        inputs = inputs.permute(1, 0)
        embeddings = self.embedding(inputs)
        embeddings = embeddings.permute(0, 2, 1)
        new_conv2 = self.maxpool1D(self.conv2(embeddings))
        new_conv3 = self.maxpool1D(self.conv3(embeddings))
        encoding = self.maxpool1D(torch.cat([new_conv2, new_conv3], dim=2))
        # print('encoding.shape: ', encoding.shape)
        h_seq, _ = self.seq_model(encoding.permute(0, 2, 1))
        # print('h_seq.shape: ', h_seq.shape)
        global_h_seq=torch.squeeze(global_max_pooling(h_seq, 1, 1)) 
        # print('h_seq.shape: ', global_h_seq.shape)
        global_h_seq = self.dropout(global_h_seq)
        outputs = self.decoder(global_h_seq)
        return outputs

In [3]:
spacy_en = English()


def tokenizer(text):  # create a tokenizer function
    """
    定义分词操作
    """
    return [tok.text for tok in spacy_en.tokenizer(text)]


def DataLoader():
    def tokenize(x): return x.split()

    TEXT = data.Field(sequential=True, tokenize=tokenizer,
                      lower=True, include_lengths=True, fix_length=40)
    LABEL = data.Field(sequential=False, use_vocab=False)
    # 假如train.csv文件并不是只有两列，比如1、3列是review和polarity，2列是我们不需要的数据，
    # 那么就要添加一个全是None的元组， fields列表存储的Field的顺序必须和csv文件中每一列的顺序对应，

    train_fields = [(None, None), ('tweet', TEXT), ('subtask_a', LABEL)]
    # train_fields = [(None, None), (None, None), (None, None), (None, None), ('text', TEXT), ('task1', LABEL)]
    train_data = data.TabularDataset(
        path='D:/Experiment/datasets/OLID/train.tsv',
        # path='D:/Experiment/datasets/EXIST2021/train.tsv',
        format='tsv',
        fields=train_fields,
        skip_header=True  # 是否跳过文件的第一行
    )
    test_fields = [(None, None), ('tweet', TEXT), ('label', LABEL)]
    # test_fields = [(None, None), (None, None), (None, None), (None, None), ('text', TEXT), ('task1', LABEL)]
    test_data = data.TabularDataset(
        path='D:/Experiment/datasets/OLID/testA.tsv',
        # path='D:/Experiment/datasets/EXIST2021/test.tsv',
        format='tsv',
        fields=test_fields,
        skip_header=True  # 是否跳过文件的第一行
    )
    return train_data, test_data, TEXT, LABEL

train_data, test_data, TEXT, LABEL = DataLoader()

vectors = Vectors(name='glove.6B.300d.txt', cache=processing.EMBEDDING_PATH)

TEXT.build_vocab(train_data,  # 建词表是用训练集建，不要用验证集和测试集
                 max_size=400000,  # 单词表容量
                 vectors=vectors,  # 还有'glove.840B.300d'已经很多可以选
                 unk_init=torch.Tensor.normal_  # 初始化train_data中不存在预训练词向量词表中的单词
                 )


In [4]:

embed_size, num_hidden, kernel_sizes, nums_channels, num_layers, dropout = 300, 100, [3, 4, 5], [100, 100, 100], 1, 0.7
model = textCNN_LSTM(len(TEXT.vocab), embed_size, num_hidden, num_layers,dropout)
model.to(DEVICE)

def init_weights(m):
    if type(m) in (nn.Linear, nn.Conv1d):
        nn.init.xavier_uniform_(m.weight)

model.apply(init_weights);

pretrained_embeddings = TEXT.vocab.vectors
# print(pretrained_embeddings.shape)
model.embedding.weight.data.copy_(pretrained_embeddings)
UNK_IDX = TEXT.vocab.stoi[TEXT.unk_token]
PAD_IDX = TEXT.vocab.stoi[TEXT.pad_token]

model.embedding.weight.data[UNK_IDX] = torch.zeros(300)
model.embedding.weight.data[PAD_IDX] = torch.zeros(300)

d:\Software\anaconda3\envs\pytorch_env\lib\site-packages\torch\nn\modules\rnn.py:62: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.7 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "


In [5]:
train_iter, test_iter = data.BucketIterator.splits(
    (train_data, test_data), batch_size=64, sort_within_batch=True, sort_key=lambda x: len(x.tweet), device=DEVICE
)

In [6]:
def train(model, train_iter, optimizer, loss, epoch):
    model.train()
    epoch_loss = 0
    num_sample = 0
    correct = 0
    for batch in tqdm(train_iter, desc=f"Training Epoch {epoch}", colour='red'):
        optimizer.zero_grad()
        text, text_len = batch.tweet
        label = batch.subtask_a
        # text, text_len = batch.text
        # label = batch.task1
        output = model(text)
        pred_y = torch.argmax(output, dim=1)
        correct += torch.sum(pred_y == label)
        l = loss(output, label)
        l.backward()
        epoch_loss += l.item()
        num_sample += len(batch)
        optimizer.step()
    print(
        f'\tTrain Loss: {epoch_loss / num_sample:.3f} | Train Acc: {correct.float() / num_sample* 100:.2f}%')


def test(model, test_iter):
    true_y, pred_y = [], []
    for batch in tqdm(test_iter, desc=f"Testing", colour='green'):
        text, text_len = batch.tweet
        label = batch.label
        # text, text_len = batch.text
        # label = batch.task1
        with torch.no_grad():
            output = model(text)
            pred_y.extend(output.argmax(dim=1).tolist())
            true_y.extend(label.tolist())
    print(metrics.confusion_matrix(true_y, pred_y))
    print(metrics.classification_report(true_y, pred_y))
    print(f'Acc : {metrics.accuracy_score(true_y, pred_y)}\t F1: {metrics.f1_score(true_y, pred_y, average="macro")}')

In [7]:
lr, num_epochs = 0.0001, 30
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
loss = nn.CrossEntropyLoss()
for epoch in range(1, num_epochs+1):
    train(model, train_iter, optimizer, loss, epoch)
    test(model, test_iter)

Training Epoch 1: 100%|██████████| 207/207 [00:02<00:00, 86.73it/s] 


	Train Loss: 0.010 | Train Acc: 66.35%


Testing: 100%|██████████| 14/14 [00:00<00:00, 449.76it/s]


[[618   2]
 [238   2]]
              precision    recall  f1-score   support

           0       0.72      1.00      0.84       620
           1       0.50      0.01      0.02       240

    accuracy                           0.72       860
   macro avg       0.61      0.50      0.43       860
weighted avg       0.66      0.72      0.61       860

Acc : 0.7209302325581395	 F1: 0.4268959083033454


Training Epoch 2: 100%|██████████| 207/207 [00:01<00:00, 108.56it/s]


	Train Loss: 0.009 | Train Acc: 69.12%


Testing: 100%|██████████| 14/14 [00:00<00:00, 461.41it/s]


[[619   1]
 [192  48]]
              precision    recall  f1-score   support

           0       0.76      1.00      0.87       620
           1       0.98      0.20      0.33       240

    accuracy                           0.78       860
   macro avg       0.87      0.60      0.60       860
weighted avg       0.82      0.78      0.72       860

Acc : 0.7755813953488372	 F1: 0.5986546055097338


Training Epoch 3: 100%|██████████| 207/207 [00:01<00:00, 111.85it/s]


	Train Loss: 0.008 | Train Acc: 76.02%


Testing: 100%|██████████| 14/14 [00:00<00:00, 491.33it/s]


[[589  31]
 [134 106]]
              precision    recall  f1-score   support

           0       0.81      0.95      0.88       620
           1       0.77      0.44      0.56       240

    accuracy                           0.81       860
   macro avg       0.79      0.70      0.72       860
weighted avg       0.80      0.81      0.79       860

Acc : 0.8081395348837209	 F1: 0.7197374736081183


Training Epoch 4: 100%|██████████| 207/207 [00:01<00:00, 112.54it/s]


	Train Loss: 0.007 | Train Acc: 79.21%


Testing: 100%|██████████| 14/14 [00:00<00:00, 473.37it/s]


[[545  75]
 [ 99 141]]
              precision    recall  f1-score   support

           0       0.85      0.88      0.86       620
           1       0.65      0.59      0.62       240

    accuracy                           0.80       860
   macro avg       0.75      0.73      0.74       860
weighted avg       0.79      0.80      0.79       860

Acc : 0.7976744186046512	 F1: 0.7403814123917387


Training Epoch 5: 100%|██████████| 207/207 [00:01<00:00, 113.43it/s]


	Train Loss: 0.007 | Train Acc: 81.48%


Testing: 100%|██████████| 14/14 [00:00<00:00, 422.58it/s]


[[594  26]
 [128 112]]
              precision    recall  f1-score   support

           0       0.82      0.96      0.89       620
           1       0.81      0.47      0.59       240

    accuracy                           0.82       860
   macro avg       0.82      0.71      0.74       860
weighted avg       0.82      0.82      0.80       860

Acc : 0.8209302325581396	 F1: 0.7389192471159685


Training Epoch 6: 100%|██████████| 207/207 [00:01<00:00, 110.86it/s]


	Train Loss: 0.006 | Train Acc: 84.47%


Testing: 100%|██████████| 14/14 [00:00<00:00, 533.29it/s]


[[580  40]
 [113 127]]
              precision    recall  f1-score   support

           0       0.84      0.94      0.88       620
           1       0.76      0.53      0.62       240

    accuracy                           0.82       860
   macro avg       0.80      0.73      0.75       860
weighted avg       0.82      0.82      0.81       860

Acc : 0.8220930232558139	 F1: 0.7537757933797538


Training Epoch 7: 100%|██████████| 207/207 [00:01<00:00, 111.82it/s]


	Train Loss: 0.005 | Train Acc: 87.35%


Testing: 100%|██████████| 14/14 [00:00<00:00, 502.02it/s]


[[582  38]
 [110 130]]
              precision    recall  f1-score   support

           0       0.84      0.94      0.89       620
           1       0.77      0.54      0.64       240

    accuracy                           0.83       860
   macro avg       0.81      0.74      0.76       860
weighted avg       0.82      0.83      0.82       860

Acc : 0.827906976744186	 F1: 0.7622250119560019


Training Epoch 8: 100%|██████████| 207/207 [00:01<00:00, 110.64it/s]


	Train Loss: 0.004 | Train Acc: 89.69%


Testing: 100%|██████████| 14/14 [00:00<00:00, 539.03it/s]


[[541  79]
 [ 92 148]]
              precision    recall  f1-score   support

           0       0.85      0.87      0.86       620
           1       0.65      0.62      0.63       240

    accuracy                           0.80       860
   macro avg       0.75      0.74      0.75       860
weighted avg       0.80      0.80      0.80       860

Acc : 0.8011627906976744	 F1: 0.7486802551819958


Training Epoch 9: 100%|██████████| 207/207 [00:01<00:00, 108.61it/s]


	Train Loss: 0.003 | Train Acc: 93.35%


Testing: 100%|██████████| 14/14 [00:00<00:00, 492.06it/s]


[[543  77]
 [ 95 145]]
              precision    recall  f1-score   support

           0       0.85      0.88      0.86       620
           1       0.65      0.60      0.63       240

    accuracy                           0.80       860
   macro avg       0.75      0.74      0.75       860
weighted avg       0.80      0.80      0.80       860

Acc : 0.8	 F1: 0.7454903337256278


Training Epoch 10: 100%|██████████| 207/207 [00:01<00:00, 112.32it/s]


	Train Loss: 0.002 | Train Acc: 95.11%


Testing: 100%|██████████| 14/14 [00:00<00:00, 500.18it/s]


[[573  47]
 [111 129]]
              precision    recall  f1-score   support

           0       0.84      0.92      0.88       620
           1       0.73      0.54      0.62       240

    accuracy                           0.82       860
   macro avg       0.79      0.73      0.75       860
weighted avg       0.81      0.82      0.81       860

Acc : 0.8162790697674419	 F1: 0.7495133317602642


Training Epoch 11: 100%|██████████| 207/207 [00:01<00:00, 114.13it/s]


	Train Loss: 0.002 | Train Acc: 96.63%


Testing: 100%|██████████| 14/14 [00:00<00:00, 438.47it/s]


[[557  63]
 [104 136]]
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       620
           1       0.68      0.57      0.62       240

    accuracy                           0.81       860
   macro avg       0.76      0.73      0.74       860
weighted avg       0.80      0.81      0.80       860

Acc : 0.8058139534883721	 F1: 0.7446115381811262


Training Epoch 12: 100%|██████████| 207/207 [00:01<00:00, 106.50it/s]


	Train Loss: 0.001 | Train Acc: 97.49%


Testing: 100%|██████████| 14/14 [00:00<00:00, 407.74it/s]


[[531  89]
 [ 95 145]]
              precision    recall  f1-score   support

           0       0.85      0.86      0.85       620
           1       0.62      0.60      0.61       240

    accuracy                           0.79       860
   macro avg       0.73      0.73      0.73       860
weighted avg       0.78      0.79      0.79       860

Acc : 0.786046511627907	 F1: 0.7320708969123135


Training Epoch 13: 100%|██████████| 207/207 [00:01<00:00, 105.61it/s]


	Train Loss: 0.001 | Train Acc: 97.91%


Testing: 100%|██████████| 14/14 [00:00<00:00, 474.24it/s]


[[506 114]
 [ 80 160]]
              precision    recall  f1-score   support

           0       0.86      0.82      0.84       620
           1       0.58      0.67      0.62       240

    accuracy                           0.77       860
   macro avg       0.72      0.74      0.73       860
weighted avg       0.79      0.77      0.78       860

Acc : 0.7744186046511627	 F1: 0.7308528692465042


Training Epoch 14: 100%|██████████| 207/207 [00:01<00:00, 104.47it/s]


	Train Loss: 0.001 | Train Acc: 98.00%


Testing: 100%|██████████| 14/14 [00:00<00:00, 430.13it/s]


[[566  54]
 [115 125]]
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       620
           1       0.70      0.52      0.60       240

    accuracy                           0.80       860
   macro avg       0.76      0.72      0.73       860
weighted avg       0.79      0.80      0.79       860

Acc : 0.8034883720930233	 F1: 0.7333793171766165


Training Epoch 15: 100%|██████████| 207/207 [00:01<00:00, 110.88it/s]


	Train Loss: 0.001 | Train Acc: 98.66%


Testing: 100%|██████████| 14/14 [00:00<00:00, 478.21it/s]


[[515 105]
 [ 86 154]]
              precision    recall  f1-score   support

           0       0.86      0.83      0.84       620
           1       0.59      0.64      0.62       240

    accuracy                           0.78       860
   macro avg       0.73      0.74      0.73       860
weighted avg       0.78      0.78      0.78       860

Acc : 0.7779069767441861	 F1: 0.7304026562543597


Training Epoch 16: 100%|██████████| 207/207 [00:01<00:00, 113.08it/s]


	Train Loss: 0.001 | Train Acc: 98.94%


Testing: 100%|██████████| 14/14 [00:00<00:00, 518.05it/s]


[[502 118]
 [ 83 157]]
              precision    recall  f1-score   support

           0       0.86      0.81      0.83       620
           1       0.57      0.65      0.61       240

    accuracy                           0.77       860
   macro avg       0.71      0.73      0.72       860
weighted avg       0.78      0.77      0.77       860

Acc : 0.7662790697674419	 F1: 0.7214518793054829


Training Epoch 17: 100%|██████████| 207/207 [00:01<00:00, 108.44it/s]


	Train Loss: 0.001 | Train Acc: 99.12%


Testing: 100%|██████████| 14/14 [00:00<00:00, 463.39it/s]


[[534  86]
 [ 99 141]]
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       620
           1       0.62      0.59      0.60       240

    accuracy                           0.78       860
   macro avg       0.73      0.72      0.73       860
weighted avg       0.78      0.78      0.78       860

Acc : 0.7848837209302325	 F1: 0.7281043696413405


Training Epoch 18: 100%|██████████| 207/207 [00:01<00:00, 110.84it/s]


	Train Loss: 0.000 | Train Acc: 99.35%


Testing: 100%|██████████| 14/14 [00:00<00:00, 510.03it/s]


[[546  74]
 [112 128]]
              precision    recall  f1-score   support

           0       0.83      0.88      0.85       620
           1       0.63      0.53      0.58       240

    accuracy                           0.78       860
   macro avg       0.73      0.71      0.72       860
weighted avg       0.78      0.78      0.78       860

Acc : 0.7837209302325582	 F1: 0.7168228071293523


Training Epoch 19: 100%|██████████| 207/207 [00:01<00:00, 113.92it/s]


	Train Loss: 0.000 | Train Acc: 99.40%


Testing: 100%|██████████| 14/14 [00:00<00:00, 511.27it/s]


[[574  46]
 [133 107]]
              precision    recall  f1-score   support

           0       0.81      0.93      0.87       620
           1       0.70      0.45      0.54       240

    accuracy                           0.79       860
   macro avg       0.76      0.69      0.70       860
weighted avg       0.78      0.79      0.78       860

Acc : 0.791860465116279	 F1: 0.7048192655571983


Training Epoch 20: 100%|██████████| 207/207 [00:01<00:00, 113.31it/s]


	Train Loss: 0.000 | Train Acc: 99.46%


Testing: 100%|██████████| 14/14 [00:00<00:00, 453.38it/s]


[[570  50]
 [128 112]]
              precision    recall  f1-score   support

           0       0.82      0.92      0.86       620
           1       0.69      0.47      0.56       240

    accuracy                           0.79       860
   macro avg       0.75      0.69      0.71       860
weighted avg       0.78      0.79      0.78       860

Acc : 0.7930232558139535	 F1: 0.7110804097871795


Training Epoch 21: 100%|██████████| 207/207 [00:01<00:00, 110.89it/s]


	Train Loss: 0.000 | Train Acc: 99.43%


Testing: 100%|██████████| 14/14 [00:00<00:00, 468.30it/s]


[[509 111]
 [ 91 149]]
              precision    recall  f1-score   support

           0       0.85      0.82      0.83       620
           1       0.57      0.62      0.60       240

    accuracy                           0.77       860
   macro avg       0.71      0.72      0.72       860
weighted avg       0.77      0.77      0.77       860

Acc : 0.7651162790697674	 F1: 0.7152131147540983


Training Epoch 22: 100%|██████████| 207/207 [00:01<00:00, 114.12it/s]


	Train Loss: 0.001 | Train Acc: 98.57%


Testing: 100%|██████████| 14/14 [00:00<00:00, 486.19it/s]


[[434 186]
 [ 63 177]]
              precision    recall  f1-score   support

           0       0.87      0.70      0.78       620
           1       0.49      0.74      0.59       240

    accuracy                           0.71       860
   macro avg       0.68      0.72      0.68       860
weighted avg       0.77      0.71      0.72       860

Acc : 0.7104651162790697	 F1: 0.6820730724176789


Training Epoch 23: 100%|██████████| 207/207 [00:01<00:00, 113.97it/s]


	Train Loss: 0.000 | Train Acc: 99.04%


Testing: 100%|██████████| 14/14 [00:00<00:00, 496.22it/s]


[[553  67]
 [108 132]]
              precision    recall  f1-score   support

           0       0.84      0.89      0.86       620
           1       0.66      0.55      0.60       240

    accuracy                           0.80       860
   macro avg       0.75      0.72      0.73       860
weighted avg       0.79      0.80      0.79       860

Acc : 0.7965116279069767	 F1: 0.7323773603694438


Training Epoch 24: 100%|██████████| 207/207 [00:01<00:00, 114.03it/s]


	Train Loss: 0.000 | Train Acc: 99.58%


Testing: 100%|██████████| 14/14 [00:00<00:00, 520.87it/s]


[[531  89]
 [104 136]]
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       620
           1       0.60      0.57      0.58       240

    accuracy                           0.78       860
   macro avg       0.72      0.71      0.72       860
weighted avg       0.77      0.78      0.77       860

Acc : 0.7755813953488372	 F1: 0.7155806880006853


Training Epoch 25: 100%|██████████| 207/207 [00:01<00:00, 110.57it/s]


	Train Loss: 0.000 | Train Acc: 99.57%


Testing: 100%|██████████| 14/14 [00:00<00:00, 459.69it/s]


[[568  52]
 [125 115]]
              precision    recall  f1-score   support

           0       0.82      0.92      0.87       620
           1       0.69      0.48      0.57       240

    accuracy                           0.79       860
   macro avg       0.75      0.70      0.72       860
weighted avg       0.78      0.79      0.78       860

Acc : 0.7941860465116279	 F1: 0.7151523884197152


Training Epoch 26: 100%|██████████| 207/207 [00:01<00:00, 107.95it/s]


	Train Loss: 0.000 | Train Acc: 99.68%


Testing: 100%|██████████| 14/14 [00:00<00:00, 425.16it/s]


[[559  61]
 [119 121]]
              precision    recall  f1-score   support

           0       0.82      0.90      0.86       620
           1       0.66      0.50      0.57       240

    accuracy                           0.79       860
   macro avg       0.74      0.70      0.72       860
weighted avg       0.78      0.79      0.78       860

Acc : 0.7906976744186046	 F1: 0.717392415601107


Training Epoch 27: 100%|██████████| 207/207 [00:01<00:00, 104.37it/s]


	Train Loss: 0.000 | Train Acc: 99.61%


Testing: 100%|██████████| 14/14 [00:00<00:00, 451.26it/s]


[[566  54]
 [121 119]]
              precision    recall  f1-score   support

           0       0.82      0.91      0.87       620
           1       0.69      0.50      0.58       240

    accuracy                           0.80       860
   macro avg       0.76      0.70      0.72       860
weighted avg       0.79      0.80      0.79       860

Acc : 0.7965116279069767	 F1: 0.721188385875274


Training Epoch 28: 100%|██████████| 207/207 [00:01<00:00, 107.38it/s]


	Train Loss: 0.000 | Train Acc: 99.68%


Testing: 100%|██████████| 14/14 [00:00<00:00, 505.48it/s]


[[564  56]
 [127 113]]
              precision    recall  f1-score   support

           0       0.82      0.91      0.86       620
           1       0.67      0.47      0.55       240

    accuracy                           0.79       860
   macro avg       0.74      0.69      0.71       860
weighted avg       0.78      0.79      0.77       860

Acc : 0.7872093023255814	 F1: 0.7064895682386576


Training Epoch 29: 100%|██████████| 207/207 [00:01<00:00, 112.51it/s]


	Train Loss: 0.000 | Train Acc: 99.64%


Testing: 100%|██████████| 14/14 [00:00<00:00, 475.63it/s]


[[559  61]
 [116 124]]
              precision    recall  f1-score   support

           0       0.83      0.90      0.86       620
           1       0.67      0.52      0.58       240

    accuracy                           0.79       860
   macro avg       0.75      0.71      0.72       860
weighted avg       0.78      0.79      0.79       860

Acc : 0.7941860465116279	 F1: 0.7234249375425845


Training Epoch 30: 100%|██████████| 207/207 [00:01<00:00, 113.35it/s]


	Train Loss: 0.000 | Train Acc: 99.65%


Testing: 100%|██████████| 14/14 [00:00<00:00, 479.08it/s]

[[561  59]
 [118 122]]
              precision    recall  f1-score   support

           0       0.83      0.90      0.86       620
           1       0.67      0.51      0.58       240

    accuracy                           0.79       860
   macro avg       0.75      0.71      0.72       860
weighted avg       0.78      0.79      0.78       860

Acc : 0.7941860465116279	 F1: 0.7216568930238682
