In [1]:
import sys
sys.path.append("D:/Experiment")
from MyKu import processing
from MyKu import training
from MyKu import MHeadAttention
import pandas as pd
from tqdm import tqdm
import pandas as pd
import torchtext
from torchtext.vocab import Vectors
from torchtext.legacy import data
import torch
from torch import nn
import torch.nn.functional as F
from d2l import torch as d2l
from torch.autograd import Variable
from spacy.lang.en import English
from sklearn import metrics

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(DEVICE)


cuda:0


In [2]:
processing.create_Sem2018()

In [3]:
def tokenizer(text):  # create a tokenizer function
    """
    定义分词操作
    """
    return processing.Pre_processing_tweets().tokenize_process(text)


def DataLoader():

    TEXT = data.Field(sequential=True, tokenize=tokenizer,
                      lower=True, include_lengths=True, fix_length=20)
    LABEL = data.Field(sequential=False, use_vocab=False)
    # 假如train.csv文件并不是只有两列，比如1、3列是review和polarity，2列是我们不需要的数据，
    # 那么就要添加一个全是None的元组， fields列表存储的Field的顺序必须和csv文件中每一列的顺序对应，

    train_fields = [(None, None), ('label', LABEL),  ('tweet', TEXT)]
    # train_fields = [(None, None), (None, None), (None, None), (None, None), ('text', TEXT), ('task1', LABEL)]
    train_data = data.TabularDataset(
        path='D:/Experiment/datasets/SEM2018/train.tsv',
        # path='D:/Experiment/datasets/EXIST2021/train.tsv',
        format='tsv',
        fields=train_fields,
        skip_header=True  # 是否跳过文件的第一行
    )
    test_fields = [(None, None), ('label', LABEL),  ('tweet', TEXT)]
    # test_fields = [(None, None), (None, None), (None, None), (None, None), ('text', TEXT), ('task1', LABEL)]
    test_data = data.TabularDataset(
        path='D:/Experiment/datasets/SEM2018/test.tsv',
        # path='D:/Experiment/datasets/EXIST2021/test.tsv',
        format='tsv',
        fields=test_fields,
        skip_header=True  # 是否跳过文件的第一行
    )
    return train_data, test_data, TEXT, LABEL


In [4]:
train_data, test_data, TEXT, LABEL = DataLoader()

vectors = Vectors(name='glove.6B.300d.txt', cache=processing.EMBEDDING_PATH)

TEXT.build_vocab(train_data,  # 建词表是用训练集建，不要用验证集和测试集
                  max_size=400000, # 单词表容量
                  vectors=vectors, # 还有'glove.840B.300d'已经很多可以选
                  unk_init=torch.Tensor.normal_ # 初始化train_data中不存在预训练词向量词表中的单词
)

In [5]:
def transpose_qkv(X, num_heads):
    """为了多注意力头的并行计算而变换形状"""
    # 输入X的形状:(batch_size，查询或者“键－值”对的个数，num_hiddens)
    # 输出X的形状:(batch_size，查询或者“键－值”对的个数，num_heads，
    # num_hiddens/num_heads)
    X = X.reshape(X.shape[0], X.shape[1], num_heads, -1)

    # 输出X的形状:(batch_size，num_heads，查询或者“键－值”对的个数,
    # num_hiddens/num_heads)
    X = X.permute(0, 2, 1, 3)

    # 最终输出的形状:(batch_size*num_heads,查询或者“键－值”对的个数,
    # num_hiddens/num_heads)
    return X.reshape(-1, X.shape[2], X.shape[3])

#@save
def transpose_output(X, num_heads):
    """逆转transpose_qkv函数的操作"""
    X = X.reshape(-1, num_heads, X.shape[1], X.shape[2])
    X = X.permute(0, 2, 1, 3)
    return X.reshape(X.shape[0], X.shape[1], -1)


class MultiHeadAttention(nn.Module):
    """多头注意力"""

    def __init__(self, key_size, query_size, value_size, num_hiddens,
                 num_heads, dropout, bias=False, **kwargs):
        super(MultiHeadAttention, self).__init__(**kwargs)
        self.num_heads = num_heads
        self.attention = d2l.DotProductAttention(dropout)
        self.W_q = nn.Linear(query_size, num_hiddens, bias=bias)
        self.W_k = nn.Linear(key_size, num_hiddens, bias=bias)
        self.W_v = nn.Linear(value_size, num_hiddens, bias=bias)
        self.W_o = nn.Linear(num_hiddens, query_size, bias=bias)

    def forward(self, queries, keys, values, valid_lens):
        # queries，keys，values的形状:
        # (batch_size，查询或者“键－值”对的个数，num_hiddens)
        # valid_lens　的形状:
        # (batch_size，)或(batch_size，查询的个数)
        # 经过变换后，输出的queries，keys，values　的形状:
        # (batch_size*num_heads，查询或者“键－值”对的个数，
        # num_hiddens/num_heads)
        queries = transpose_qkv(self.W_q(queries), self.num_heads)
        keys = transpose_qkv(self.W_k(keys), self.num_heads)
        values = transpose_qkv(self.W_v(values), self.num_heads)

        if valid_lens is not None:
            # 在轴0，将第一项（标量或者矢量）复制num_heads次，
            # 然后如此复制第二项，然后诸如此类。
            valid_lens = torch.repeat_interleave(
                valid_lens, repeats=self.num_heads, dim=0)
        # output的形状:(batch_size*num_heads，查询的个数，
        # num_hiddens/num_heads)
        output = self.attention(queries, keys, values, valid_lens)

        # output_concat的形状:(batch_size，查询的个数，num_hiddens)
        output_concat = transpose_output(output, self.num_heads)
        output = self.W_o(output_concat)
        return output


In [17]:

class MModel(nn.Module):
    def __init__(self,vocab_size, embed_size, num_hiddens, output_dim, max_length, num_layers, dropout, **kwargs):
        super(MModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.LSTM = nn.LSTM(embed_size, num_hiddens, num_layers=num_layers, bidirectional=True, dropout=dropout, batch_first=True)
        self.n_class = output_dim
        self.max_length = max_length
        self.attention = MultiHeadAttention(max_length, max_length, max_length, max_length, 5, 0.5)
        self.decoder1 = nn.Linear(num_hiddens * 4, max_length)
        self.decoder2 = nn.Linear(num_hiddens, self.n_class)
        self.dense = nn.Linear(embed_size, max_length)
        self.U = nn.Parameter(torch.Tensor(max_length, output_dim))
        self.V = nn.Parameter(torch.Tensor(num_hiddens, output_dim))
        self.g = nn.Parameter(torch.Tensor(max_length))
        self.W_f = nn.Parameter(torch.Tensor(output_dim, output_dim))
        self.bias = nn.Parameter(torch.Tensor(output_dim))
        nn.init.uniform_(self.U, -0.1, 0.1)
        nn.init.uniform_(self.V, -0.1, 0.1)
        nn.init.uniform_(self.g, -0.1, 0.1)
        nn.init.uniform_(self.W_f, -0.1, 0.1)
        nn.init.uniform_(self.bias, -0.1, 0.1)
    
    def forward(self, inputs, text_lens): #inputs torch.Size([64, 40])
        input = self.embedding(inputs.permute(1, 0)) #input torch.Size([64, 40, 300])
        valid_lens = text_lens
        att_input = self.dense(input)
        self_attention = self.attention(att_input, att_input, att_input, valid_lens)  # self_attention torch.size([64, 40, 40])
        # print(self_attention.shape)
        att_score, idxs = torch.max(self_attention, dim=1)   # att_score torch.Size([64, 40])
        self.LSTM.flatten_parameters()
        outputs, _ = self.LSTM(input)    #outputs torch.Size([64, 40, 200])
        output = torch.cat((outputs[:,0,:], outputs[:,-1,:]), dim=1)    # output torch.Size([64, 400])
        output = self.decoder1(output)      # output torch.Size([64, 100])
        # outs = self.decoder2(output)
        f_a = torch.matmul(att_score, self.U)   # output torch.Size([64, 2])
        f_b = torch.matmul(output, self.V)  # output torch.Size([64, 2])
        f = f_a.mul(f_b) + self.g   # output torch.Size([64, 2])
        outs = torch.softmax(torch.matmul(f, self.W_f) + self.bias, dim=1)
        return outs


In [14]:

def train(model, train_iter, optimizer, loss, epoch):
    model.train()
    epoch_loss = 0
    num_sample = 0
    correct = 0
    for batch in tqdm(train_iter, desc=f"Training Epoch {epoch}", colour='red'):
        optimizer.zero_grad()
        text, text_len = batch.tweet
        label = batch.label
        # text, text_len = batch.text
        # label = batch.task1
        output = model(text, text_len)
        pred_y = torch.argmax(output, dim=1)
        correct += torch.sum(pred_y == label)
        l = loss(output, label)
        l.backward()
        epoch_loss += l.item()
        num_sample += len(batch)
        optimizer.step()
    print(
        f'\tTrain Loss: {epoch_loss / num_sample:.3f} | Train Acc: {correct.float() / num_sample* 100:.2f}%')


def test(model, test_iter):
    true_y, pred_y = [], []
    for batch in tqdm(test_iter, desc=f"Testing", colour='green'):
        text, text_len = batch.tweet
        label = batch.label
        # text, text_len = batch.text
        # label = batch.task1
        with torch.no_grad():
            output = model(text, text_len)
            pred_y.extend(output.argmax(dim=1).tolist())
            true_y.extend(label.tolist())
    print(metrics.confusion_matrix(true_y, pred_y))
    print(metrics.classification_report(true_y, pred_y))
    print(f'Acc : {metrics.accuracy_score(true_y, pred_y)}\t F1: {metrics.f1_score(true_y, pred_y, average="macro")}')


In [32]:
num_hiddens, output_dim, max_length, num_layers, dropout = 100, 2, 20, 2, 0.7
model = MModel(len(TEXT.vocab), 300, num_hiddens, output_dim, max_length, num_layers, dropout)
model.to(DEVICE)
pretrained_embeddings = TEXT.vocab.vectors
    # print(pretrained_embeddings.shape)
model.embedding.weight.data.copy_(pretrained_embeddings)
UNK_IDX = TEXT.vocab.stoi[TEXT.unk_token]
PAD_IDX = TEXT.vocab.stoi[TEXT.pad_token]

model.embedding.weight.data[UNK_IDX] = torch.zeros(300)
model.embedding.weight.data[PAD_IDX] = torch.zeros(300)


train_iter, test_iter = data.BucketIterator.splits((train_data, test_data), batch_size=64, sort_within_batch=True, sort_key=lambda x: len(x.tweet), device=DEVICE)


In [36]:
lr, num_epochs = 0.0001, 20

optimizer = torch.optim.Adam(model.parameters(), lr=lr)
loss = nn.CrossEntropyLoss()
for epoch in range(1, num_epochs+1):
    train(model, train_iter, optimizer, loss, epoch)
    test(model, test_iter)


Training Epoch 1: 100%|██████████| 60/60 [00:00<00:00, 62.71it/s]


	Train Loss: 0.006 | Train Acc: 90.86%


Testing: 100%|██████████| 13/13 [00:00<00:00, 249.77it/s]


[[319 154]
 [140 171]]
              precision    recall  f1-score   support

           0       0.69      0.67      0.68       473
           1       0.53      0.55      0.54       311

    accuracy                           0.62       784
   macro avg       0.61      0.61      0.61       784
weighted avg       0.63      0.62      0.63       784

Acc : 0.625	 F1: 0.6111426026398898


Training Epoch 2: 100%|██████████| 60/60 [00:00<00:00, 73.07it/s]


	Train Loss: 0.006 | Train Acc: 90.78%


Testing: 100%|██████████| 13/13 [00:00<00:00, 231.93it/s]


[[309 164]
 [134 177]]
              precision    recall  f1-score   support

           0       0.70      0.65      0.67       473
           1       0.52      0.57      0.54       311

    accuracy                           0.62       784
   macro avg       0.61      0.61      0.61       784
weighted avg       0.63      0.62      0.62       784

Acc : 0.6198979591836735	 F1: 0.6088086371795216


Training Epoch 3: 100%|██████████| 60/60 [00:00<00:00, 69.68it/s]


	Train Loss: 0.006 | Train Acc: 91.14%


Testing: 100%|██████████| 13/13 [00:00<00:00, 207.60it/s]


[[279 194]
 [111 200]]
              precision    recall  f1-score   support

           0       0.72      0.59      0.65       473
           1       0.51      0.64      0.57       311

    accuracy                           0.61       784
   macro avg       0.61      0.62      0.61       784
weighted avg       0.63      0.61      0.62       784

Acc : 0.610969387755102	 F1: 0.6069787891488541


Training Epoch 4: 100%|██████████| 60/60 [00:00<00:00, 73.52it/s]


	Train Loss: 0.006 | Train Acc: 91.33%


Testing: 100%|██████████| 13/13 [00:00<00:00, 196.79it/s]


[[304 169]
 [132 179]]
              precision    recall  f1-score   support

           0       0.70      0.64      0.67       473
           1       0.51      0.58      0.54       311

    accuracy                           0.62       784
   macro avg       0.61      0.61      0.61       784
weighted avg       0.62      0.62      0.62       784

Acc : 0.6160714285714286	 F1: 0.606057115574987


Training Epoch 5: 100%|██████████| 60/60 [00:00<00:00, 74.63it/s]


	Train Loss: 0.006 | Train Acc: 91.14%


Testing: 100%|██████████| 13/13 [00:00<00:00, 202.94it/s]


[[221 252]
 [ 77 234]]
              precision    recall  f1-score   support

           0       0.74      0.47      0.57       473
           1       0.48      0.75      0.59       311

    accuracy                           0.58       784
   macro avg       0.61      0.61      0.58       784
weighted avg       0.64      0.58      0.58       784

Acc : 0.5803571428571429	 F1: 0.5802417300935576


Training Epoch 6: 100%|██████████| 60/60 [00:00<00:00, 76.17it/s]


	Train Loss: 0.006 | Train Acc: 90.62%


Testing: 100%|██████████| 13/13 [00:00<00:00, 231.93it/s]


[[285 188]
 [118 193]]
              precision    recall  f1-score   support

           0       0.71      0.60      0.65       473
           1       0.51      0.62      0.56       311

    accuracy                           0.61       784
   macro avg       0.61      0.61      0.60       784
weighted avg       0.63      0.61      0.61       784

Acc : 0.6096938775510204	 F1: 0.6042441998574708


Training Epoch 7: 100%|██████████| 60/60 [00:00<00:00, 75.82it/s]


	Train Loss: 0.006 | Train Acc: 90.88%


Testing: 100%|██████████| 13/13 [00:00<00:00, 236.15it/s]


[[303 170]
 [129 182]]
              precision    recall  f1-score   support

           0       0.70      0.64      0.67       473
           1       0.52      0.59      0.55       311

    accuracy                           0.62       784
   macro avg       0.61      0.61      0.61       784
weighted avg       0.63      0.62      0.62       784

Acc : 0.6186224489795918	 F1: 0.6093164337558229


Training Epoch 8: 100%|██████████| 60/60 [00:00<00:00, 75.53it/s]


	Train Loss: 0.006 | Train Acc: 91.17%


Testing: 100%|██████████| 13/13 [00:00<00:00, 236.15it/s]


[[269 204]
 [109 202]]
              precision    recall  f1-score   support

           0       0.71      0.57      0.63       473
           1       0.50      0.65      0.56       311

    accuracy                           0.60       784
   macro avg       0.60      0.61      0.60       784
weighted avg       0.63      0.60      0.60       784

Acc : 0.6007653061224489	 F1: 0.597828135575998


Training Epoch 9: 100%|██████████| 60/60 [00:00<00:00, 75.47it/s]


	Train Loss: 0.006 | Train Acc: 91.09%


Testing: 100%|██████████| 13/13 [00:00<00:00, 220.14it/s]


[[336 137]
 [148 163]]
              precision    recall  f1-score   support

           0       0.69      0.71      0.70       473
           1       0.54      0.52      0.53       311

    accuracy                           0.64       784
   macro avg       0.62      0.62      0.62       784
weighted avg       0.63      0.64      0.64       784

Acc : 0.6364795918367347	 F1: 0.617872956097461


Training Epoch 10: 100%|██████████| 60/60 [00:00<00:00, 75.94it/s]


	Train Loss: 0.006 | Train Acc: 91.46%


Testing: 100%|██████████| 13/13 [00:00<00:00, 240.52it/s]


[[321 152]
 [143 168]]
              precision    recall  f1-score   support

           0       0.69      0.68      0.69       473
           1       0.53      0.54      0.53       311

    accuracy                           0.62       784
   macro avg       0.61      0.61      0.61       784
weighted avg       0.63      0.62      0.62       784

Acc : 0.6237244897959183	 F1: 0.6088267678313801


Training Epoch 11: 100%|██████████| 60/60 [00:00<00:00, 75.45it/s]


	Train Loss: 0.006 | Train Acc: 91.33%


Testing: 100%|██████████| 13/13 [00:00<00:00, 220.14it/s]


[[299 174]
 [125 186]]
              precision    recall  f1-score   support

           0       0.71      0.63      0.67       473
           1       0.52      0.60      0.55       311

    accuracy                           0.62       784
   macro avg       0.61      0.62      0.61       784
weighted avg       0.63      0.62      0.62       784

Acc : 0.6186224489795918	 F1: 0.6105315449577745


Training Epoch 12: 100%|██████████| 60/60 [00:00<00:00, 68.62it/s]


	Train Loss: 0.006 | Train Acc: 91.51%


Testing: 100%|██████████| 13/13 [00:00<00:00, 209.48it/s]


[[280 193]
 [112 199]]
              precision    recall  f1-score   support

           0       0.71      0.59      0.65       473
           1       0.51      0.64      0.57       311

    accuracy                           0.61       784
   macro avg       0.61      0.62      0.61       784
weighted avg       0.63      0.61      0.62       784

Acc : 0.610969387755102	 F1: 0.6067719681957588


Training Epoch 13: 100%|██████████| 60/60 [00:00<00:00, 63.97it/s]


	Train Loss: 0.006 | Train Acc: 91.43%


Testing: 100%|██████████| 13/13 [00:00<00:00, 202.94it/s]


[[228 245]
 [ 77 234]]
              precision    recall  f1-score   support

           0       0.75      0.48      0.59       473
           1       0.49      0.75      0.59       311

    accuracy                           0.59       784
   macro avg       0.62      0.62      0.59       784
weighted avg       0.64      0.59      0.59       784

Acc : 0.5892857142857143	 F1: 0.5892616576095798


Training Epoch 14: 100%|██████████| 60/60 [00:00<00:00, 63.53it/s]


	Train Loss: 0.007 | Train Acc: 89.55%


Testing: 100%|██████████| 13/13 [00:00<00:00, 216.47it/s]


[[226 247]
 [ 78 233]]
              precision    recall  f1-score   support

           0       0.74      0.48      0.58       473
           1       0.49      0.75      0.59       311

    accuracy                           0.59       784
   macro avg       0.61      0.61      0.59       784
weighted avg       0.64      0.59      0.58       784

Acc : 0.5854591836734694	 F1: 0.5854261340987004


Training Epoch 15: 100%|██████████| 60/60 [00:00<00:00, 64.69it/s]


	Train Loss: 0.007 | Train Acc: 89.89%


Testing: 100%|██████████| 13/13 [00:00<00:00, 232.10it/s]


[[312 161]
 [128 183]]
              precision    recall  f1-score   support

           0       0.71      0.66      0.68       473
           1       0.53      0.59      0.56       311

    accuracy                           0.63       784
   macro avg       0.62      0.62      0.62       784
weighted avg       0.64      0.63      0.63       784

Acc : 0.6313775510204082	 F1: 0.6211198715751276


Training Epoch 16: 100%|██████████| 60/60 [00:00<00:00, 64.21it/s]


	Train Loss: 0.006 | Train Acc: 91.01%


Testing: 100%|██████████| 13/13 [00:00<00:00, 193.86it/s]


[[285 188]
 [114 197]]
              precision    recall  f1-score   support

           0       0.71      0.60      0.65       473
           1       0.51      0.63      0.57       311

    accuracy                           0.61       784
   macro avg       0.61      0.62      0.61       784
weighted avg       0.63      0.61      0.62       784

Acc : 0.6147959183673469	 F1: 0.6098808393968154


Training Epoch 17: 100%|██████████| 60/60 [00:00<00:00, 66.04it/s]


	Train Loss: 0.006 | Train Acc: 91.30%


Testing: 100%|██████████| 13/13 [00:00<00:00, 202.94it/s]


[[334 139]
 [145 166]]
              precision    recall  f1-score   support

           0       0.70      0.71      0.70       473
           1       0.54      0.53      0.54       311

    accuracy                           0.64       784
   macro avg       0.62      0.62      0.62       784
weighted avg       0.64      0.64      0.64       784

Acc : 0.6377551020408163	 F1: 0.6203208556149733


Training Epoch 18: 100%|██████████| 60/60 [00:00<00:00, 64.76it/s]


	Train Loss: 0.006 | Train Acc: 91.07%


Testing: 100%|██████████| 13/13 [00:00<00:00, 223.93it/s]


[[281 192]
 [110 201]]
              precision    recall  f1-score   support

           0       0.72      0.59      0.65       473
           1       0.51      0.65      0.57       311

    accuracy                           0.61       784
   macro avg       0.62      0.62      0.61       784
weighted avg       0.64      0.61      0.62       784

Acc : 0.6147959183673469	 F1: 0.610742845117845


Training Epoch 19: 100%|██████████| 60/60 [00:00<00:00, 66.34it/s]


	Train Loss: 0.006 | Train Acc: 91.33%


Testing: 100%|██████████| 13/13 [00:00<00:00, 209.48it/s]


[[314 159]
 [132 179]]
              precision    recall  f1-score   support

           0       0.70      0.66      0.68       473
           1       0.53      0.58      0.55       311

    accuracy                           0.63       784
   macro avg       0.62      0.62      0.62       784
weighted avg       0.63      0.63      0.63       784

Acc : 0.6288265306122449	 F1: 0.6174846713199011


Training Epoch 20: 100%|██████████| 60/60 [00:00<00:00, 71.83it/s]


	Train Loss: 0.006 | Train Acc: 91.67%


Testing: 100%|██████████| 13/13 [00:00<00:00, 245.06it/s]

[[279 194]
 [111 200]]
              precision    recall  f1-score   support

           0       0.72      0.59      0.65       473
           1       0.51      0.64      0.57       311

    accuracy                           0.61       784
   macro avg       0.61      0.62      0.61       784
weighted avg       0.63      0.61      0.62       784

Acc : 0.610969387755102	 F1: 0.6069787891488541
