In [1]:
import pandas as pd
import torchtext
from torchtext.vocab import Vectors
from torchtext.legacy import data
import torch
from torch import nn
import torch.nn.functional as F
from d2l import torch as d2l
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence
from torch.autograd import Variable
from sklearn import metrics
import sys
sys.path.append("D:/Experiment")
from tqdm import tqdm
from MyKu import training
from MyKu import processing
from torchtext.vocab import Vectors
from spacy.lang.en import English

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(DEVICE)


cuda:0


In [2]:
processing.create_OLID()
# processing.set_olid_train_data(processing.ORIGIN_DATASET_PATH + '/OLID')
# processing.set_olid_testA_data(processing.ORIGIN_DATASET_PATH + '/OLID')


In [3]:
# train_data = processing.get_OLID_train_data(processing.OLID_DATASET + '/train.tsv')
# test_data = processing.get_OLID_testA_data(
#     processing.OLID_DATASET + '/testA.tsv', processing.OLID_DATASET + '/labels-levela.csv')


In [4]:
spacy_en = English()

def tokenizer(text):  # create a tokenizer function
    """
    定义分词操作
    """
    return [tok.text for tok in spacy_en.tokenizer(text)]

def DataLoader():
    def tokenize(x): return x.split()

    TEXT = data.Field(sequential=True, tokenize=tokenizer, lower=True, include_lengths=True, fix_length=40)
    LABEL = data.Field(sequential=False, use_vocab=False)
    # 假如train.csv文件并不是只有两列，比如1、3列是review和polarity，2列是我们不需要的数据，
    # 那么就要添加一个全是None的元组， fields列表存储的Field的顺序必须和csv文件中每一列的顺序对应，

    train_fields = [(None, None), ('tweet', TEXT), ('subtask_a', LABEL)]
    # train_fields = [(None, None), (None, None), (None, None), (None, None), ('text', TEXT), ('task1', LABEL)]
    train_data= data.TabularDataset(
    path='D:/Experiment/datasets/OLID/train.tsv',
    # path='D:/Experiment/datasets/EXIST2021/train.tsv',
    format='tsv',
    fields=train_fields,
    skip_header=True  # 是否跳过文件的第一行
    )
    test_fields = [(None, None), ('tweet', TEXT), ('label', LABEL)]
    # test_fields = [(None, None), (None, None), (None, None), (None, None), ('text', TEXT), ('task1', LABEL)]
    test_data= data.TabularDataset(
    path='D:/Experiment/datasets/OLID/testA.tsv',
    # path='D:/Experiment/datasets/EXIST2021/test.tsv',
    format='tsv',
        fields=test_fields,
    skip_header=True  # 是否跳过文件的第一行
    )
    return train_data, test_data, TEXT, LABEL


In [5]:
train_data, test_data, TEXT, LABEL = DataLoader()
# x1, x2 = 1, 1
# for index in train_data:
#     index.task1 = 1 if index.task1 == 'sexist' else 0

# for index in test_data:
#     index.task1 = 1 if index.task1 == 'sexist' else 0

# temp_examples = []
# for index in train_data.examples:
#     if len(index.text) == 0:
#         continue
#     if x1 > 3437:
#         break
#     else:
#         x1 += 1
#     temp_examples.append(index)
# train_data.examples = temp_examples
# temp_examples = []
# for index in test_data.examples:
#     if len(index.text) == 0:
#         continue
#     if x2 > 1000:
#         break
#     else:
#         x2 += 1
#     temp_examples.append(index)
# test_data.examples = temp_examples

vectors = Vectors(name='glove.6B.300d.txt', cache=processing.EMBEDDING_PATH)

TEXT.build_vocab(train_data,  # 建词表是用训练集建，不要用验证集和测试集
                  max_size=400000, # 单词表容量
                  vectors=vectors, # 还有'glove.840B.300d'已经很多可以选
                  unk_init=torch.Tensor.normal_ # 初始化train_data中不存在预训练词向量词表中的单词
)

In [6]:
from operator import truediv

# BiLSTM + Attention 
class BiRNN(nn.Module):
    def __init__(self, vocab_size, embed_size, num_hiddens, num_layers, n_class, bidirectional, dropout, **kwargs):
        super(BiRNN, self).__init__(**kwargs)
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.encoder = nn.LSTM(
            embed_size, num_hiddens, num_layers=num_layers, bidirectional=True, dropout=dropout, batch_first=True)
        self.n_class = n_class  # 类别数
        self.bidirectional = bidirectional  # 控制是否双向LSTM
        if self.bidirectional:
            self.decoder1 = nn.Linear(num_hiddens * 2, num_hiddens)
            self.decoder2 = nn.Linear(num_hiddens, n_class)
        else:
            self.decoder1 = nn.Linear(num_hiddens * 2, num_hiddens)
            self.decoder2 = nn.Linear(num_hiddens, n_class)
        self.weight_W = nn.Parameter(torch.Tensor(2 * num_hiddens, 2 * num_hiddens))
        self.weight_proj = nn.Parameter(torch.Tensor(2 * num_hiddens, 1))
        self.t = nn.Parameter(torch.Tensor(num_hiddens, 2))
        nn.init.uniform_(self.weight_W, -0.1, 0.1)
        nn.init.uniform_(self.weight_proj, -0.1, 0.1)


    def forward(self, inputs):
        embeddings = self.embedding(inputs)
        # print(embeddings.shape)
        self.encoder.flatten_parameters()
        outputs, _ = self.encoder(embeddings.permute(1, 0, 2))
        # print(outputs.shape)
        u = torch.tanh(torch.matmul(outputs, self.weight_W))
        # print(u.shape)
        att = torch.matmul(u, self.weight_proj)
        att_score = F.softmax(att, dim=1)
        # print(att_score.shape)
        score_x = outputs * att_score
        encoding = torch.sum(score_x, dim=1)
        # encoding = torch.cat((outputs[0], outputs[-1]), dim=1)
        outs = self.decoder1(encoding)
        outs = self.decoder2(outs)
        # print(outs.shape)
        return outs


In [7]:
tt = torch.zeros([2, 10])
ss = torch.ones(10)
s = ss.view(1, 10)
res = tt + s
res

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
# X = torch.ones((4, 6), dtype=torch.long).to(device=DEVICE)
model = BiRNN(len(TEXT.vocab), 300, 200, 1, 2, True, 0.5)
model.to(DEVICE)

d:\Software\anaconda3\envs\pytorch_env\lib\site-packages\torch\nn\modules\rnn.py:62: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "


BiRNN(
  (embedding): Embedding(20148, 300)
  (encoder): LSTM(300, 200, batch_first=True, dropout=0.5, bidirectional=True)
  (decoder1): Linear(in_features=400, out_features=200, bias=True)
  (decoder2): Linear(in_features=200, out_features=2, bias=True)
)

In [9]:
pretrained_embeddings = TEXT.vocab.vectors
# print(pretrained_embeddings.shape)
model.embedding.weight.data.copy_(pretrained_embeddings)
UNK_IDX = TEXT.vocab.stoi[TEXT.unk_token]
PAD_IDX = TEXT.vocab.stoi[TEXT.pad_token]

model.embedding.weight.data[UNK_IDX] = torch.zeros(300)
model.embedding.weight.data[PAD_IDX] = torch.zeros(300)

In [10]:
train_iter, test_iter = data.BucketIterator.splits(
    (train_data, test_data), batch_size=64, sort_within_batch=True, sort_key=lambda x : len(x.tweet), device=DEVICE
)

In [11]:
def train(model, train_iter, optimizer, loss, epoch):
    model.train()
    epoch_loss = 0
    num_sample = 0
    correct = 0
    for batch in tqdm(train_iter, desc=f"Training Epoch {epoch}", colour='red'):
        optimizer.zero_grad()
        text, text_len = batch.tweet
        label = batch.subtask_a
        # text, text_len = batch.text
        # label = batch.task1
        output = model(text)
        pred_y = torch.argmax(output, dim=1)
        correct += torch.sum(pred_y == label)
        l = loss(output, label)
        l.backward()
        epoch_loss += l.item()
        num_sample += len(batch)
        optimizer.step()
    print(
        f'\tTrain Loss: {epoch_loss / num_sample:.3f} | Train Acc: {correct.float() / num_sample* 100:.2f}%')


def test(model, test_iter):
    true_y, pred_y = [], []
    for batch in tqdm(test_iter, desc=f"Testing", colour='green'):
        text, text_len = batch.tweet
        label = batch.label
        # text, text_len = batch.text
        # label = batch.task1
        with torch.no_grad():
            output = model(text)
            pred_y.extend(output.argmax(dim=1).tolist())
            true_y.extend(label.tolist())
    print(metrics.confusion_matrix(true_y, pred_y))
    print(metrics.classification_report(true_y, pred_y))
    print(f'Acc : {metrics.accuracy_score(true_y, pred_y)}\t F1: {metrics.f1_score(true_y, pred_y, average="macro")}')


In [12]:
lr, num_epochs = 0.0001, 20
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
loss = nn.CrossEntropyLoss()
for epoch in range(1, num_epochs+1):
    train(model, train_iter, optimizer, loss, epoch)
    test(model, test_iter)

Training Epoch 1: 100%|██████████| 207/207 [00:03<00:00, 60.22it/s]


	Train Loss: 0.009 | Train Acc: 68.80%


Testing: 100%|██████████| 14/14 [00:00<00:00, 191.61it/s]


[[590  30]
 [134 106]]
              precision    recall  f1-score   support

           0       0.81      0.95      0.88       620
           1       0.78      0.44      0.56       240

    accuracy                           0.81       860
   macro avg       0.80      0.70      0.72       860
weighted avg       0.81      0.81      0.79       860

Acc : 0.8093023255813954	 F1: 0.7209029888551166


Training Epoch 2: 100%|██████████| 207/207 [00:03<00:00, 66.00it/s]


	Train Loss: 0.007 | Train Acc: 77.79%


Testing: 100%|██████████| 14/14 [00:00<00:00, 208.76it/s]


[[583  37]
 [114 126]]
              precision    recall  f1-score   support

           0       0.84      0.94      0.89       620
           1       0.77      0.53      0.63       240

    accuracy                           0.82       860
   macro avg       0.80      0.73      0.76       860
weighted avg       0.82      0.82      0.81       860

Acc : 0.8244186046511628	 F1: 0.7553278279268433


Training Epoch 3: 100%|██████████| 207/207 [00:03<00:00, 66.87it/s]


	Train Loss: 0.007 | Train Acc: 79.04%


Testing: 100%|██████████| 14/14 [00:00<00:00, 194.26it/s]


[[581  39]
 [109 131]]
              precision    recall  f1-score   support

           0       0.84      0.94      0.89       620
           1       0.77      0.55      0.64       240

    accuracy                           0.83       860
   macro avg       0.81      0.74      0.76       860
weighted avg       0.82      0.83      0.82       860

Acc : 0.827906976744186	 F1: 0.7630236455036306


Training Epoch 4: 100%|██████████| 207/207 [00:03<00:00, 68.06it/s]


	Train Loss: 0.007 | Train Acc: 80.39%


Testing: 100%|██████████| 14/14 [00:00<00:00, 215.19it/s]


[[569  51]
 [ 93 147]]
              precision    recall  f1-score   support

           0       0.86      0.92      0.89       620
           1       0.74      0.61      0.67       240

    accuracy                           0.83       860
   macro avg       0.80      0.77      0.78       860
weighted avg       0.83      0.83      0.83       860

Acc : 0.8325581395348837	 F1: 0.7794541918663048


Training Epoch 5: 100%|██████████| 207/207 [00:03<00:00, 67.70it/s]


	Train Loss: 0.006 | Train Acc: 81.55%


Testing: 100%|██████████| 14/14 [00:00<00:00, 218.55it/s]


[[575  45]
 [101 139]]
              precision    recall  f1-score   support

           0       0.85      0.93      0.89       620
           1       0.76      0.58      0.66       240

    accuracy                           0.83       860
   macro avg       0.80      0.75      0.77       860
weighted avg       0.82      0.83      0.82       860

Acc : 0.8302325581395349	 F1: 0.771503028185418


Training Epoch 6: 100%|██████████| 207/207 [00:03<00:00, 68.41it/s]


	Train Loss: 0.006 | Train Acc: 82.91%


Testing: 100%|██████████| 14/14 [00:00<00:00, 222.02it/s]


[[564  56]
 [ 89 151]]
              precision    recall  f1-score   support

           0       0.86      0.91      0.89       620
           1       0.73      0.63      0.68       240

    accuracy                           0.83       860
   macro avg       0.80      0.77      0.78       860
weighted avg       0.83      0.83      0.83       860

Acc : 0.8313953488372093	 F1: 0.7808555245672029


Training Epoch 7: 100%|██████████| 207/207 [00:03<00:00, 68.71it/s]


	Train Loss: 0.005 | Train Acc: 84.71%


Testing: 100%|██████████| 14/14 [00:00<00:00, 229.30it/s]


[[573  47]
 [ 94 146]]
              precision    recall  f1-score   support

           0       0.86      0.92      0.89       620
           1       0.76      0.61      0.67       240

    accuracy                           0.84       860
   macro avg       0.81      0.77      0.78       860
weighted avg       0.83      0.84      0.83       860

Acc : 0.836046511627907	 F1: 0.7824038932583968


Training Epoch 8: 100%|██████████| 207/207 [00:03<00:00, 63.80it/s]


	Train Loss: 0.005 | Train Acc: 86.41%


Testing: 100%|██████████| 14/14 [00:00<00:00, 194.27it/s]


[[583  37]
 [106 134]]
              precision    recall  f1-score   support

           0       0.85      0.94      0.89       620
           1       0.78      0.56      0.65       240

    accuracy                           0.83       860
   macro avg       0.81      0.75      0.77       860
weighted avg       0.83      0.83      0.82       860

Acc : 0.8337209302325581	 F1: 0.7714122145208449


Training Epoch 9: 100%|██████████| 207/207 [00:03<00:00, 63.49it/s]


	Train Loss: 0.004 | Train Acc: 88.28%


Testing: 100%|██████████| 14/14 [00:00<00:00, 208.77it/s]


[[564  56]
 [ 96 144]]
              precision    recall  f1-score   support

           0       0.85      0.91      0.88       620
           1       0.72      0.60      0.65       240

    accuracy                           0.82       860
   macro avg       0.79      0.75      0.77       860
weighted avg       0.82      0.82      0.82       860

Acc : 0.8232558139534883	 F1: 0.7678977272727273


Training Epoch 10: 100%|██████████| 207/207 [00:03<00:00, 63.46it/s]


	Train Loss: 0.004 | Train Acc: 90.05%


Testing: 100%|██████████| 14/14 [00:00<00:00, 205.70it/s]


[[556  64]
 [ 92 148]]
              precision    recall  f1-score   support

           0       0.86      0.90      0.88       620
           1       0.70      0.62      0.65       240

    accuracy                           0.82       860
   macro avg       0.78      0.76      0.77       860
weighted avg       0.81      0.82      0.81       860

Acc : 0.8186046511627907	 F1: 0.7659194327349879


Training Epoch 11: 100%|██████████| 207/207 [00:03<00:00, 66.97it/s]


	Train Loss: 0.003 | Train Acc: 91.56%


Testing: 100%|██████████| 14/14 [00:00<00:00, 199.82it/s]


[[564  56]
 [102 138]]
              precision    recall  f1-score   support

           0       0.85      0.91      0.88       620
           1       0.71      0.57      0.64       240

    accuracy                           0.82       860
   macro avg       0.78      0.74      0.76       860
weighted avg       0.81      0.82      0.81       860

Acc : 0.8162790697674419	 F1: 0.7565415570733385


Training Epoch 12: 100%|██████████| 207/207 [00:03<00:00, 67.43it/s]


	Train Loss: 0.003 | Train Acc: 93.47%


Testing: 100%|██████████| 14/14 [00:00<00:00, 222.02it/s]


[[568  52]
 [112 128]]
              precision    recall  f1-score   support

           0       0.84      0.92      0.87       620
           1       0.71      0.53      0.61       240

    accuracy                           0.81       860
   macro avg       0.77      0.72      0.74       860
weighted avg       0.80      0.81      0.80       860

Acc : 0.8093023255813954	 F1: 0.7416849816849818


Training Epoch 13: 100%|██████████| 207/207 [00:03<00:00, 67.65it/s]


	Train Loss: 0.002 | Train Acc: 94.41%


Testing: 100%|██████████| 14/14 [00:00<00:00, 186.50it/s]


[[566  54]
 [113 127]]
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       620
           1       0.70      0.53      0.60       240

    accuracy                           0.81       860
   macro avg       0.77      0.72      0.74       860
weighted avg       0.80      0.81      0.80       860

Acc : 0.8058139534883721	 F1: 0.7373824922880564


Training Epoch 14: 100%|██████████| 207/207 [00:03<00:00, 65.08it/s]


	Train Loss: 0.002 | Train Acc: 95.75%


Testing: 100%|██████████| 14/14 [00:00<00:00, 211.93it/s]


[[562  58]
 [114 126]]
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       620
           1       0.68      0.53      0.59       240

    accuracy                           0.80       860
   macro avg       0.76      0.72      0.73       860
weighted avg       0.79      0.80      0.79       860

Acc : 0.8	 F1: 0.7308117866293967


Training Epoch 15: 100%|██████████| 207/207 [00:03<00:00, 65.13it/s]


	Train Loss: 0.001 | Train Acc: 96.91%


Testing: 100%|██████████| 14/14 [00:00<00:00, 199.82it/s]


[[554  66]
 [109 131]]
              precision    recall  f1-score   support

           0       0.84      0.89      0.86       620
           1       0.66      0.55      0.60       240

    accuracy                           0.80       860
   macro avg       0.75      0.72      0.73       860
weighted avg       0.79      0.80      0.79       860

Acc : 0.7965116279069767	 F1: 0.7315716347019909


Training Epoch 16: 100%|██████████| 207/207 [00:03<00:00, 65.14it/s]


	Train Loss: 0.001 | Train Acc: 97.57%


Testing: 100%|██████████| 14/14 [00:00<00:00, 197.00it/s]


[[550  70]
 [111 129]]
              precision    recall  f1-score   support

           0       0.83      0.89      0.86       620
           1       0.65      0.54      0.59       240

    accuracy                           0.79       860
   macro avg       0.74      0.71      0.72       860
weighted avg       0.78      0.79      0.78       860

Acc : 0.7895348837209303	 F1: 0.7232017270106817


Training Epoch 17: 100%|██████████| 207/207 [00:03<00:00, 62.51it/s]


	Train Loss: 0.001 | Train Acc: 97.97%


Testing: 100%|██████████| 14/14 [00:00<00:00, 181.65it/s]


[[561  59]
 [121 119]]
              precision    recall  f1-score   support

           0       0.82      0.90      0.86       620
           1       0.67      0.50      0.57       240

    accuracy                           0.79       860
   macro avg       0.75      0.70      0.72       860
weighted avg       0.78      0.79      0.78       860

Acc : 0.7906976744186046	 F1: 0.7155645712521773


Training Epoch 18: 100%|██████████| 207/207 [00:03<00:00, 62.88it/s]


	Train Loss: 0.001 | Train Acc: 98.23%


Testing: 100%|██████████| 14/14 [00:00<00:00, 202.71it/s]


[[556  64]
 [117 123]]
              precision    recall  f1-score   support

           0       0.83      0.90      0.86       620
           1       0.66      0.51      0.58       240

    accuracy                           0.79       860
   macro avg       0.74      0.70      0.72       860
weighted avg       0.78      0.79      0.78       860

Acc : 0.7895348837209303	 F1: 0.7180639400410425


Training Epoch 19: 100%|██████████| 207/207 [00:03<00:00, 65.85it/s]


	Train Loss: 0.001 | Train Acc: 98.69%


Testing: 100%|██████████| 14/14 [00:00<00:00, 205.70it/s]


[[573  47]
 [122 118]]
              precision    recall  f1-score   support

           0       0.82      0.92      0.87       620
           1       0.72      0.49      0.58       240

    accuracy                           0.80       860
   macro avg       0.77      0.71      0.73       860
weighted avg       0.79      0.80      0.79       860

Acc : 0.8034883720930233	 F1: 0.7270994695582782


Training Epoch 20: 100%|██████████| 207/207 [00:03<00:00, 67.53it/s]


	Train Loss: 0.001 | Train Acc: 98.67%


Testing: 100%|██████████| 14/14 [00:00<00:00, 215.19it/s]

[[540  80]
 [112 128]]
              precision    recall  f1-score   support

           0       0.83      0.87      0.85       620
           1       0.62      0.53      0.57       240

    accuracy                           0.78       860
   macro avg       0.72      0.70      0.71       860
weighted avg       0.77      0.78      0.77       860

Acc : 0.7767441860465116	 F1: 0.7102425876010782
