In [1]:
import pandas as pd
import warnings
from sklearn import metrics
import processing
import time
import os
from tqdm import tqdm
from torch.optim import Adam
from torch import nn
import numpy as np
import sys
sys.path.append("D:/Experiment")
import torch
from MyKu import processing
from MyKu import MyXLM_Base
warnings.filterwarnings("ignore")


In [2]:

# 训练准备阶段，设置超参数和全局变量
file_name = 'readme_taskB.md'
batch_size = 32
num_epoch = 20  # 训练轮次
check_step = 1  # 用以训练中途对模型进行检验：每check_step个epoch进行一次测试和保存模型

learning_rate = 1e-5  # 优化器的学习率

# 获取训练、测试数据、分类类别总数
en_train_data, en_test_data, de_train_data, de_test_data, hi_train_data, hi_test_data = processing.load_hasoc2020_for_taskB()
categories = 3

en_train_iter, en_test_iter = MyXLM_Base.load_xlm_data(en_train_data, en_test_data, batch_size)
de_train_iter, de_test_iter = MyXLM_Base.load_xlm_data(de_train_data, de_test_data, batch_size)
hi_train_iter, hi_test_iter = MyXLM_Base.load_xlm_data(hi_train_data, hi_test_data, batch_size)
#固定写法，可以牢记，cuda代表Gpu
# torch.cuda.is_available()可以查看当前Gpu是否可用
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 加载预训练模型，因为这里是英文数据集，需要用在英文上的预训练模型：bert-base-uncased
# uncased指该预训练模型对应的词表不区分字母的大小写
# 详情可了解：https://huggingface.co/bert-base-uncased
pretrained_model_name = 'xlm-roberta-base'
# 创建模型 BertSST2Model
model = MyXLM_Base.MyXlmModel(categories, pretrained_model_name)
# 固定写法，将模型加载到device上，
# 如果是GPU上运行，此时可以观察到GPU的显存增加
model.to(device)

# 训练过程
# Adam是最近较为常用的优化器，详情可查看：https://www.jianshu.com/p/aebcaf8af76e
optimizer = Adam(model.parameters(), learning_rate)  # 使用Adam优化器
loss = nn.CrossEntropyLoss()  # 使用crossentropy作为二分类任务的损失函数

# 记录当前训练时间，用以记录日志和存储
timestamp = time.strftime("%m_%d_%H_%M", time.localtime())


In [4]:
# TaskB

file_name = 'readme_taskB.md'
model_save_path = 'D:/Experiment_models_save/twitter-xlm-roberta-base-sentiment/hasoc2020/'
name = 'base_taskB.pth'
en_temp_best = 0.7
de_temp_best = 0.7
hi_temp_best = 0.5
for epoch in range(1, num_epoch + 1):
    MyXLM_Base.train(model, en_train_iter, device, optimizer, loss, epoch)
    MyXLM_Base.train(model, de_train_iter, device, optimizer, loss, epoch)
    MyXLM_Base.train(model, hi_train_iter, device, optimizer, loss, epoch)
    en_acc_score = MyXLM_Base.test(model, en_test_iter, device, epoch, file_name)
    de_acc_score = MyXLM_Base.test(model, de_test_iter, device, epoch, file_name)
    hi_acc_score = MyXLM_Base.test(model, hi_test_iter, device, epoch, file_name)
    print('\n\n')
    if en_acc_score > en_temp_best and de_acc_score > de_temp_best and hi_acc_score > hi_temp_best:
        en_temp_best, de_temp_best, hi_temp_best = en_acc_score, de_acc_score, hi_acc_score
        MyXLM_Base.save_pretrained(model, model_save_path, name)
        print(f'best en_acc_socre : {en_acc_score}, best de_acc_score : {de_acc_score}, best hi_acc_score : {hi_acc_score}')
print(f'best en_acc_socre : {en_temp_best}, best de_acc_score : {de_temp_best}, best de_acc_score : {hi_temp_best}')


Testing: 100%|██████████| 807/807 [00:08<00:00, 98.01it/s] 


[[533  15  32]
 [112  32  25]
 [ 29   4  25]]
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       580
           1       0.63      0.19      0.29       169
           2       0.30      0.43      0.36        58

    accuracy                           0.73       807
   macro avg       0.57      0.51      0.50       807
weighted avg       0.72      0.73      0.70       807

Acc : 0.7311028500619579	 F1: 0.49937723095617836


Testing: 100%|██████████| 300/300 [00:02<00:00, 101.02it/s]


[[136  12  29]
 [ 26  20  20]
 [  3   2  52]]
              precision    recall  f1-score   support

           0       0.82      0.77      0.80       177
           1       0.59      0.30      0.40        66
           2       0.51      0.91      0.66        57

    accuracy                           0.69       300
   macro avg       0.64      0.66      0.62       300
weighted avg       0.71      0.69      0.68       300

Acc : 0.6933333333333334	 F1: 0.6178498285093889


Testing: 100%|██████████| 367/367 [00:04<00:00, 84.58it/s]


[[27 30  6]
 [40 86 65]
 [23 26 64]]
              precision    recall  f1-score   support

           0       0.30      0.43      0.35        63
           1       0.61      0.45      0.52       191
           2       0.47      0.57      0.52       113

    accuracy                           0.48       367
   macro avg       0.46      0.48      0.46       367
weighted avg       0.51      0.48      0.49       367

Acc : 0.4822888283378747	 F1: 0.46186224174838975





Testing: 100%|██████████| 807/807 [00:08<00:00, 98.36it/s] 


[[162 401  17]
 [  5 159   5]
 [  3  42  13]]
              precision    recall  f1-score   support

           0       0.95      0.28      0.43       580
           1       0.26      0.94      0.41       169
           2       0.37      0.22      0.28        58

    accuracy                           0.41       807
   macro avg       0.53      0.48      0.37       807
weighted avg       0.77      0.41      0.42       807

Acc : 0.4138785625774473	 F1: 0.3746737514469409


Testing: 100%|██████████| 300/300 [00:03<00:00, 92.77it/s] 


[[ 19 143  15]
 [  4  58   4]
 [  0  13  44]]
              precision    recall  f1-score   support

           0       0.83      0.11      0.19       177
           1       0.27      0.88      0.41        66
           2       0.70      0.77      0.73        57

    accuracy                           0.40       300
   macro avg       0.60      0.59      0.45       300
weighted avg       0.68      0.40      0.34       300

Acc : 0.4033333333333333	 F1: 0.4458730158730158


Testing: 100%|██████████| 367/367 [00:04<00:00, 80.34it/s]


[[  2  52   9]
 [  1 143  47]
 [  0  52  61]]
              precision    recall  f1-score   support

           0       0.67      0.03      0.06        63
           1       0.58      0.75      0.65       191
           2       0.52      0.54      0.53       113

    accuracy                           0.56       367
   macro avg       0.59      0.44      0.41       367
weighted avg       0.58      0.56      0.51       367

Acc : 0.5613079019073569	 F1: 0.4146696265814788





Testing: 100%|██████████| 807/807 [00:08<00:00, 99.42it/s] 


[[482  88  10]
 [ 77  84   8]
 [ 18  28  12]]
              precision    recall  f1-score   support

           0       0.84      0.83      0.83       580
           1       0.42      0.50      0.46       169
           2       0.40      0.21      0.27        58

    accuracy                           0.72       807
   macro avg       0.55      0.51      0.52       807
weighted avg       0.72      0.72      0.71       807

Acc : 0.7162329615861215	 F1: 0.5204003694000953


Testing: 100%|██████████| 300/300 [00:03<00:00, 85.21it/s]


[[111  51  15]
 [ 13  48   5]
 [  2   8  47]]
              precision    recall  f1-score   support

           0       0.88      0.63      0.73       177
           1       0.45      0.73      0.55        66
           2       0.70      0.82      0.76        57

    accuracy                           0.69       300
   macro avg       0.68      0.73      0.68       300
weighted avg       0.75      0.69      0.70       300

Acc : 0.6866666666666666	 F1: 0.681883692751151


Testing: 100%|██████████| 367/367 [00:04<00:00, 86.15it/s]


[[ 13  41   9]
 [  3 115  73]
 [  7  42  64]]
              precision    recall  f1-score   support

           0       0.57      0.21      0.30        63
           1       0.58      0.60      0.59       191
           2       0.44      0.57      0.49       113

    accuracy                           0.52       367
   macro avg       0.53      0.46      0.46       367
weighted avg       0.53      0.52      0.51       367

Acc : 0.5231607629427792	 F1: 0.46259790523555694





Testing: 100%|██████████| 807/807 [00:08<00:00, 93.30it/s] 


[[551  19  10]
 [119  42   8]
 [ 32  10  16]]
              precision    recall  f1-score   support

           0       0.78      0.95      0.86       580
           1       0.59      0.25      0.35       169
           2       0.47      0.28      0.35        58

    accuracy                           0.75       807
   macro avg       0.62      0.49      0.52       807
weighted avg       0.72      0.75      0.72       807

Acc : 0.7546468401486989	 F1: 0.5191401569106243


Testing: 100%|██████████| 300/300 [00:03<00:00, 88.47it/s]


[[146  16  15]
 [ 25  35   6]
 [  5   4  48]]
              precision    recall  f1-score   support

           0       0.83      0.82      0.83       177
           1       0.64      0.53      0.58        66
           2       0.70      0.84      0.76        57

    accuracy                           0.76       300
   macro avg       0.72      0.73      0.72       300
weighted avg       0.76      0.76      0.76       300

Acc : 0.7633333333333333	 F1: 0.7225375420070245


Testing: 100%|██████████| 367/367 [00:04<00:00, 88.65it/s]


[[ 19  34  10]
 [ 20 108  63]
 [ 10  32  71]]
              precision    recall  f1-score   support

           0       0.39      0.30      0.34        63
           1       0.62      0.57      0.59       191
           2       0.49      0.63      0.55       113

    accuracy                           0.54       367
   macro avg       0.50      0.50      0.49       367
weighted avg       0.54      0.54      0.54       367

Acc : 0.5395095367847411	 F1: 0.49453190636096656



best en_acc_socre : 0.7546468401486989, best de_acc_score : 0.7633333333333333, best hi_acc_score : 0.5395095367847411


Testing: 100%|██████████| 807/807 [00:09<00:00, 88.61it/s]


[[520  42  18]
 [ 96  64   9]
 [ 30  10  18]]
              precision    recall  f1-score   support

           0       0.80      0.90      0.85       580
           1       0.55      0.38      0.45       169
           2       0.40      0.31      0.35        58

    accuracy                           0.75       807
   macro avg       0.59      0.53      0.55       807
weighted avg       0.72      0.75      0.73       807

Acc : 0.7459727385377943	 F1: 0.5489748275618382


Testing: 100%|██████████| 300/300 [00:03<00:00, 93.87it/s]


[[120  38  19]
 [ 16  42   8]
 [  3   8  46]]
              precision    recall  f1-score   support

           0       0.86      0.68      0.76       177
           1       0.48      0.64      0.55        66
           2       0.63      0.81      0.71        57

    accuracy                           0.69       300
   macro avg       0.66      0.71      0.67       300
weighted avg       0.73      0.69      0.70       300

Acc : 0.6933333333333334	 F1: 0.670880174677643


Testing: 100%|██████████| 367/367 [00:04<00:00, 91.44it/s]


[[ 10  48   5]
 [  8 112  71]
 [  2  34  77]]
              precision    recall  f1-score   support

           0       0.50      0.16      0.24        63
           1       0.58      0.59      0.58       191
           2       0.50      0.68      0.58       113

    accuracy                           0.54       367
   macro avg       0.53      0.48      0.47       367
weighted avg       0.54      0.54      0.52       367

Acc : 0.5422343324250681	 F1: 0.4672431352203071





Testing: 100%|██████████| 807/807 [00:08<00:00, 90.47it/s]


[[542  30   8]
 [119  46   4]
 [ 33  14  11]]
              precision    recall  f1-score   support

           0       0.78      0.93      0.85       580
           1       0.51      0.27      0.36       169
           2       0.48      0.19      0.27        58

    accuracy                           0.74       807
   macro avg       0.59      0.47      0.49       807
weighted avg       0.70      0.74      0.71       807

Acc : 0.7422552664188352	 F1: 0.4925602385919847


Testing: 100%|██████████| 300/300 [00:03<00:00, 98.17it/s] 


[[134  29  14]
 [ 25  33   8]
 [  4   5  48]]
              precision    recall  f1-score   support

           0       0.82      0.76      0.79       177
           1       0.49      0.50      0.50        66
           2       0.69      0.84      0.76        57

    accuracy                           0.72       300
   macro avg       0.67      0.70      0.68       300
weighted avg       0.72      0.72      0.72       300

Acc : 0.7166666666666667	 F1: 0.68012713581081


Testing: 100%|██████████| 367/367 [00:04<00:00, 91.39it/s]


[[ 13  45   5]
 [ 13 144  34]
 [  9  50  54]]
              precision    recall  f1-score   support

           0       0.37      0.21      0.27        63
           1       0.60      0.75      0.67       191
           2       0.58      0.48      0.52       113

    accuracy                           0.57       367
   macro avg       0.52      0.48      0.49       367
weighted avg       0.56      0.57      0.56       367

Acc : 0.5749318801089919	 F1: 0.48644846965654626





Testing: 100%|██████████| 807/807 [00:08<00:00, 95.54it/s] 


[[486  74  20]
 [ 87  74   8]
 [ 21  21  16]]
              precision    recall  f1-score   support

           0       0.82      0.84      0.83       580
           1       0.44      0.44      0.44       169
           2       0.36      0.28      0.31        58

    accuracy                           0.71       807
   macro avg       0.54      0.52      0.53       807
weighted avg       0.71      0.71      0.71       807

Acc : 0.7137546468401487	 F1: 0.5265113279636086


Testing: 100%|██████████| 300/300 [00:03<00:00, 96.75it/s] 


[[106  58  13]
 [ 14  48   4]
 [  4   9  44]]
              precision    recall  f1-score   support

           0       0.85      0.60      0.70       177
           1       0.42      0.73      0.53        66
           2       0.72      0.77      0.75        57

    accuracy                           0.66       300
   macro avg       0.66      0.70      0.66       300
weighted avg       0.73      0.66      0.67       300

Acc : 0.66	 F1: 0.6601561296909916


Testing: 100%|██████████| 367/367 [00:03<00:00, 94.09it/s]


[[  9  52   2]
 [  7 148  36]
 [  4  62  47]]
              precision    recall  f1-score   support

           0       0.45      0.14      0.22        63
           1       0.56      0.77      0.65       191
           2       0.55      0.42      0.47       113

    accuracy                           0.56       367
   macro avg       0.52      0.44      0.45       367
weighted avg       0.54      0.56      0.52       367

Acc : 0.555858310626703	 F1: 0.4483455260603589





Testing: 100%|██████████| 807/807 [00:08<00:00, 97.77it/s] 


[[529  34  17]
 [106  50  13]
 [ 26  15  17]]
              precision    recall  f1-score   support

           0       0.80      0.91      0.85       580
           1       0.51      0.30      0.37       169
           2       0.36      0.29      0.32        58

    accuracy                           0.74       807
   macro avg       0.56      0.50      0.52       807
weighted avg       0.71      0.74      0.71       807

Acc : 0.7385377942998761	 F1: 0.5164940425839796


Testing: 100%|██████████| 300/300 [00:02<00:00, 101.84it/s]


[[135  29  13]
 [ 20  37   9]
 [  2   6  49]]
              precision    recall  f1-score   support

           0       0.86      0.76      0.81       177
           1       0.51      0.56      0.54        66
           2       0.69      0.86      0.77        57

    accuracy                           0.74       300
   macro avg       0.69      0.73      0.70       300
weighted avg       0.75      0.74      0.74       300

Acc : 0.7366666666666667	 F1: 0.7034133725303017


Testing: 100%|██████████| 367/367 [00:04<00:00, 86.56it/s]


[[ 17  40   6]
 [ 12 143  36]
 [ 13  54  46]]
              precision    recall  f1-score   support

           0       0.40      0.27      0.32        63
           1       0.60      0.75      0.67       191
           2       0.52      0.41      0.46       113

    accuracy                           0.56       367
   macro avg       0.51      0.48      0.48       367
weighted avg       0.54      0.56      0.54       367

Acc : 0.5613079019073569	 F1: 0.48324842188700473





Testing: 100%|██████████| 807/807 [00:08<00:00, 98.65it/s] 


[[515  42  23]
 [ 98  57  14]
 [ 25  13  20]]
              precision    recall  f1-score   support

           0       0.81      0.89      0.85       580
           1       0.51      0.34      0.41       169
           2       0.35      0.34      0.35        58

    accuracy                           0.73       807
   macro avg       0.56      0.52      0.53       807
weighted avg       0.71      0.73      0.72       807

Acc : 0.7335811648079306	 F1: 0.5330562138012506


Testing: 100%|██████████| 300/300 [00:02<00:00, 100.82it/s]


[[127  34  16]
 [ 17  40   9]
 [  5   5  47]]
              precision    recall  f1-score   support

           0       0.85      0.72      0.78       177
           1       0.51      0.61      0.55        66
           2       0.65      0.82      0.73        57

    accuracy                           0.71       300
   macro avg       0.67      0.72      0.69       300
weighted avg       0.74      0.71      0.72       300

Acc : 0.7133333333333334	 F1: 0.6865158042560496


Testing: 100%|██████████| 367/367 [00:04<00:00, 80.52it/s]


[[ 14  42   7]
 [ 13 148  30]
 [  6  63  44]]
              precision    recall  f1-score   support

           0       0.42      0.22      0.29        63
           1       0.58      0.77      0.67       191
           2       0.54      0.39      0.45       113

    accuracy                           0.56       367
   macro avg       0.52      0.46      0.47       367
weighted avg       0.54      0.56      0.54       367

Acc : 0.5613079019073569	 F1: 0.47064719358533796





Testing: 100%|██████████| 807/807 [00:07<00:00, 101.92it/s]


[[533  32  15]
 [104  58   7]
 [ 30  13  15]]
              precision    recall  f1-score   support

           0       0.80      0.92      0.85       580
           1       0.56      0.34      0.43       169
           2       0.41      0.26      0.32        58

    accuracy                           0.75       807
   macro avg       0.59      0.51      0.53       807
weighted avg       0.72      0.75      0.73       807

Acc : 0.7509293680297398	 F1: 0.5323705686216579


Testing: 100%|██████████| 300/300 [00:03<00:00, 84.88it/s]


[[131  33  13]
 [ 19  43   4]
 [  4  10  43]]
              precision    recall  f1-score   support

           0       0.85      0.74      0.79       177
           1       0.50      0.65      0.57        66
           2       0.72      0.75      0.74        57

    accuracy                           0.72       300
   macro avg       0.69      0.72      0.70       300
weighted avg       0.75      0.72      0.73       300

Acc : 0.7233333333333334	 F1: 0.6974576647418117


Testing: 100%|██████████| 367/367 [00:04<00:00, 83.41it/s]


[[ 22  31  10]
 [ 25 127  39]
 [ 13  44  56]]
              precision    recall  f1-score   support

           0       0.37      0.35      0.36        63
           1       0.63      0.66      0.65       191
           2       0.53      0.50      0.51       113

    accuracy                           0.56       367
   macro avg       0.51      0.50      0.51       367
weighted avg       0.55      0.56      0.56       367

Acc : 0.55858310626703	 F1: 0.5059318258985517





Testing: 100%|██████████| 807/807 [00:08<00:00, 95.64it/s] 


[[527  42  11]
 [103  58   8]
 [ 29  15  14]]
              precision    recall  f1-score   support

           0       0.80      0.91      0.85       580
           1       0.50      0.34      0.41       169
           2       0.42      0.24      0.31        58

    accuracy                           0.74       807
   macro avg       0.58      0.50      0.52       807
weighted avg       0.71      0.74      0.72       807

Acc : 0.7422552664188352	 F1: 0.5222763496814583


Testing: 100%|██████████| 300/300 [00:03<00:00, 86.10it/s]


[[132  31  14]
 [ 22  39   5]
 [  7   5  45]]
              precision    recall  f1-score   support

           0       0.82      0.75      0.78       177
           1       0.52      0.59      0.55        66
           2       0.70      0.79      0.74        57

    accuracy                           0.72       300
   macro avg       0.68      0.71      0.69       300
weighted avg       0.73      0.72      0.72       300

Acc : 0.72	 F1: 0.692686077003887


Testing: 100%|██████████| 367/367 [00:04<00:00, 88.57it/s]


[[ 14  41   8]
 [ 11 135  45]
 [  9  53  51]]
              precision    recall  f1-score   support

           0       0.41      0.22      0.29        63
           1       0.59      0.71      0.64       191
           2       0.49      0.45      0.47       113

    accuracy                           0.54       367
   macro avg       0.50      0.46      0.47       367
weighted avg       0.53      0.54      0.53       367

Acc : 0.5449591280653951	 F1: 0.46718767320696153





Testing: 100%|██████████| 807/807 [00:08<00:00, 91.72it/s] 


[[495  58  27]
 [ 92  65  12]
 [ 19  19  20]]
              precision    recall  f1-score   support

           0       0.82      0.85      0.83       580
           1       0.46      0.38      0.42       169
           2       0.34      0.34      0.34        58

    accuracy                           0.72       807
   macro avg       0.54      0.53      0.53       807
weighted avg       0.71      0.72      0.71       807

Acc : 0.7187112763320942	 F1: 0.5315417966497279


Testing: 100%|██████████| 300/300 [00:03<00:00, 93.99it/s]


[[123  37  17]
 [ 17  41   8]
 [  3   4  50]]
              precision    recall  f1-score   support

           0       0.86      0.69      0.77       177
           1       0.50      0.62      0.55        66
           2       0.67      0.88      0.76        57

    accuracy                           0.71       300
   macro avg       0.68      0.73      0.69       300
weighted avg       0.74      0.71      0.72       300

Acc : 0.7133333333333334	 F1: 0.6934599372099374


Testing: 100%|██████████| 367/367 [00:04<00:00, 91.55it/s]


[[ 13  41   9]
 [  7 134  50]
 [  1  52  60]]
              precision    recall  f1-score   support

           0       0.62      0.21      0.31        63
           1       0.59      0.70      0.64       191
           2       0.50      0.53      0.52       113

    accuracy                           0.56       367
   macro avg       0.57      0.48      0.49       367
weighted avg       0.57      0.56      0.55       367

Acc : 0.5640326975476839	 F1: 0.489304504731002





Testing: 100%|██████████| 807/807 [00:09<00:00, 87.13it/s]


[[545  25  10]
 [117  47   5]
 [ 34  12  12]]
              precision    recall  f1-score   support

           0       0.78      0.94      0.85       580
           1       0.56      0.28      0.37       169
           2       0.44      0.21      0.28        58

    accuracy                           0.75       807
   macro avg       0.60      0.47      0.50       807
weighted avg       0.71      0.75      0.71       807

Acc : 0.748451053283767	 F1: 0.5027088060247951


Testing: 100%|██████████| 300/300 [00:03<00:00, 97.31it/s] 


[[142  22  13]
 [ 27  31   8]
 [  7   6  44]]
              precision    recall  f1-score   support

           0       0.81      0.80      0.80       177
           1       0.53      0.47      0.50        66
           2       0.68      0.77      0.72        57

    accuracy                           0.72       300
   macro avg       0.67      0.68      0.67       300
weighted avg       0.72      0.72      0.72       300

Acc : 0.7233333333333334	 F1: 0.6739480177711729


Testing: 100%|██████████| 367/367 [00:04<00:00, 90.80it/s]


[[ 21  39   3]
 [  9 135  47]
 [  5  55  53]]
              precision    recall  f1-score   support

           0       0.60      0.33      0.43        63
           1       0.59      0.71      0.64       191
           2       0.51      0.47      0.49       113

    accuracy                           0.57       367
   macro avg       0.57      0.50      0.52       367
weighted avg       0.57      0.57      0.56       367

Acc : 0.5694822888283378	 F1: 0.5207231040564374





Testing: 100%|██████████| 807/807 [00:08<00:00, 90.70it/s] 


[[569   7   4]
 [130  35   4]
 [ 39   8  11]]
              precision    recall  f1-score   support

           0       0.77      0.98      0.86       580
           1       0.70      0.21      0.32       169
           2       0.58      0.19      0.29        58

    accuracy                           0.76       807
   macro avg       0.68      0.46      0.49       807
weighted avg       0.74      0.76      0.71       807

Acc : 0.7620817843866171	 F1: 0.4895928091512934


Testing: 100%|██████████| 300/300 [00:03<00:00, 99.12it/s] 


[[156  14   7]
 [ 30  28   8]
 [  8   6  43]]
              precision    recall  f1-score   support

           0       0.80      0.88      0.84       177
           1       0.58      0.42      0.49        66
           2       0.74      0.75      0.75        57

    accuracy                           0.76       300
   macro avg       0.71      0.69      0.69       300
weighted avg       0.74      0.76      0.75       300

Acc : 0.7566666666666667	 F1: 0.6933415025120911


Testing: 100%|██████████| 367/367 [00:03<00:00, 94.59it/s]


[[ 17  38   8]
 [ 11 126  54]
 [  6  48  59]]
              precision    recall  f1-score   support

           0       0.50      0.27      0.35        63
           1       0.59      0.66      0.63       191
           2       0.49      0.52      0.50       113

    accuracy                           0.55       367
   macro avg       0.53      0.48      0.49       367
weighted avg       0.55      0.55      0.54       367

Acc : 0.5504087193460491	 F1: 0.4933663806294335





Testing: 100%|██████████| 807/807 [00:08<00:00, 96.18it/s] 


[[547  26   7]
 [118  48   3]
 [ 36  12  10]]
              precision    recall  f1-score   support

           0       0.78      0.94      0.85       580
           1       0.56      0.28      0.38       169
           2       0.50      0.17      0.26        58

    accuracy                           0.75       807
   macro avg       0.61      0.47      0.50       807
weighted avg       0.71      0.75      0.71       807

Acc : 0.7496902106567535	 F1: 0.4956337137629327


Testing: 100%|██████████| 300/300 [00:02<00:00, 100.82it/s]


[[150  18   9]
 [ 30  29   7]
 [ 10   6  41]]
              precision    recall  f1-score   support

           0       0.79      0.85      0.82       177
           1       0.55      0.44      0.49        66
           2       0.72      0.72      0.72        57

    accuracy                           0.73       300
   macro avg       0.69      0.67      0.67       300
weighted avg       0.72      0.73      0.73       300

Acc : 0.7333333333333333	 F1: 0.6747106318984404


Testing: 100%|██████████| 367/367 [00:03<00:00, 93.82it/s]


[[ 22  35   6]
 [ 22 128  41]
 [ 12  49  52]]
              precision    recall  f1-score   support

           0       0.39      0.35      0.37        63
           1       0.60      0.67      0.64       191
           2       0.53      0.46      0.49       113

    accuracy                           0.55       367
   macro avg       0.51      0.49      0.50       367
weighted avg       0.54      0.55      0.55       367

Acc : 0.5504087193460491	 F1: 0.49851655630181274





Testing: 100%|██████████| 807/807 [00:08<00:00, 98.34it/s] 


[[569   4   7]
 [130  35   4]
 [ 38   8  12]]
              precision    recall  f1-score   support

           0       0.77      0.98      0.86       580
           1       0.74      0.21      0.32       169
           2       0.52      0.21      0.30        58

    accuracy                           0.76       807
   macro avg       0.68      0.47      0.49       807
weighted avg       0.75      0.76      0.71       807

Acc : 0.7633209417596035	 F1: 0.49481847071064994


Testing: 100%|██████████| 300/300 [00:02<00:00, 102.16it/s]


[[157  14   6]
 [ 32  26   8]
 [  6   4  47]]
              precision    recall  f1-score   support

           0       0.81      0.89      0.84       177
           1       0.59      0.39      0.47        66
           2       0.77      0.82      0.80        57

    accuracy                           0.77       300
   macro avg       0.72      0.70      0.70       300
weighted avg       0.75      0.77      0.75       300

Acc : 0.7666666666666667	 F1: 0.7044744879080582


Testing: 100%|██████████| 367/367 [00:04<00:00, 84.84it/s]


[[ 23  31   9]
 [ 25 121  45]
 [ 11  34  68]]
              precision    recall  f1-score   support

           0       0.39      0.37      0.38        63
           1       0.65      0.63      0.64       191
           2       0.56      0.60      0.58       113

    accuracy                           0.58       367
   macro avg       0.53      0.53      0.53       367
weighted avg       0.58      0.58      0.58       367

Acc : 0.5776566757493188	 F1: 0.5325607996355984



best en_acc_socre : 0.7633209417596035, best de_acc_score : 0.7666666666666667, best hi_acc_score : 0.5776566757493188


Testing: 100%|██████████| 807/807 [00:07<00:00, 101.56it/s]


[[562  12   6]
 [123  42   4]
 [ 31  15  12]]
              precision    recall  f1-score   support

           0       0.78      0.97      0.87       580
           1       0.61      0.25      0.35       169
           2       0.55      0.21      0.30        58

    accuracy                           0.76       807
   macro avg       0.65      0.47      0.51       807
weighted avg       0.73      0.76      0.72       807

Acc : 0.7633209417596035	 F1: 0.5067417090292907


Testing: 100%|██████████| 300/300 [00:03<00:00, 88.52it/s]


[[154  15   8]
 [ 32  26   8]
 [  7   9  41]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.83       177
           1       0.52      0.39      0.45        66
           2       0.72      0.72      0.72        57

    accuracy                           0.74       300
   macro avg       0.68      0.66      0.67       300
weighted avg       0.72      0.74      0.73       300

Acc : 0.7366666666666667	 F1: 0.6666688467051444


Testing: 100%|██████████| 367/367 [00:04<00:00, 82.78it/s]


[[ 24  31   8]
 [ 15 132  44]
 [ 11  47  55]]
              precision    recall  f1-score   support

           0       0.48      0.38      0.42        63
           1       0.63      0.69      0.66       191
           2       0.51      0.49      0.50       113

    accuracy                           0.57       367
   macro avg       0.54      0.52      0.53       367
weighted avg       0.57      0.57      0.57       367

Acc : 0.5749318801089919	 F1: 0.5277109585917211





Testing: 100%|██████████| 807/807 [00:08<00:00, 96.64it/s] 


[[530  38  12]
 [104  56   9]
 [ 28  16  14]]
              precision    recall  f1-score   support

           0       0.80      0.91      0.85       580
           1       0.51      0.33      0.40       169
           2       0.40      0.24      0.30        58

    accuracy                           0.74       807
   macro avg       0.57      0.50      0.52       807
weighted avg       0.71      0.74      0.72       807

Acc : 0.7434944237918215	 F1: 0.5186570394611535


Testing: 100%|██████████| 300/300 [00:03<00:00, 85.49it/s]


[[137  27  13]
 [ 24  34   8]
 [  5  11  41]]
              precision    recall  f1-score   support

           0       0.83      0.77      0.80       177
           1       0.47      0.52      0.49        66
           2       0.66      0.72      0.69        57

    accuracy                           0.71       300
   macro avg       0.65      0.67      0.66       300
weighted avg       0.72      0.71      0.71       300

Acc : 0.7066666666666667	 F1: 0.6602210242274964


Testing: 100%|██████████| 367/367 [00:04<00:00, 89.91it/s]


[[ 21  38   4]
 [ 20 138  33]
 [ 14  59  40]]
              precision    recall  f1-score   support

           0       0.38      0.33      0.36        63
           1       0.59      0.72      0.65       191
           2       0.52      0.35      0.42       113

    accuracy                           0.54       367
   macro avg       0.50      0.47      0.47       367
weighted avg       0.53      0.54      0.53       367

Acc : 0.5422343324250681	 F1: 0.4749573863041466





Testing: 100%|██████████| 807/807 [00:08<00:00, 91.23it/s] 


[[545  24  11]
 [113  47   9]
 [ 33  12  13]]
              precision    recall  f1-score   support

           0       0.79      0.94      0.86       580
           1       0.57      0.28      0.37       169
           2       0.39      0.22      0.29        58

    accuracy                           0.75       807
   macro avg       0.58      0.48      0.51       807
weighted avg       0.71      0.75      0.72       807

Acc : 0.7496902106567535	 F1: 0.5054408685407897


Testing: 100%|██████████| 300/300 [00:03<00:00, 92.51it/s]


[[145  18  14]
 [ 28  30   8]
 [  4   7  46]]
              precision    recall  f1-score   support

           0       0.82      0.82      0.82       177
           1       0.55      0.45      0.50        66
           2       0.68      0.81      0.74        57

    accuracy                           0.74       300
   macro avg       0.68      0.69      0.68       300
weighted avg       0.73      0.74      0.73       300

Acc : 0.7366666666666667	 F1: 0.6836922693810212


Testing: 100%|██████████| 367/367 [00:03<00:00, 92.43it/s]


[[ 20  37   6]
 [  9 145  37]
 [  8  50  55]]
              precision    recall  f1-score   support

           0       0.54      0.32      0.40        63
           1       0.62      0.76      0.69       191
           2       0.56      0.49      0.52       113

    accuracy                           0.60       367
   macro avg       0.58      0.52      0.54       367
weighted avg       0.59      0.60      0.59       367

Acc : 0.5994550408719346	 F1: 0.5356354034785012





Testing: 100%|██████████| 807/807 [00:09<00:00, 88.05it/s]


[[548  25   7]
 [115  52   2]
 [ 34   9  15]]
              precision    recall  f1-score   support

           0       0.79      0.94      0.86       580
           1       0.60      0.31      0.41       169
           2       0.62      0.26      0.37        58

    accuracy                           0.76       807
   macro avg       0.67      0.50      0.54       807
weighted avg       0.74      0.76      0.73       807

Acc : 0.7620817843866171	 F1: 0.5439861154334976


Testing: 100%|██████████| 300/300 [00:03<00:00, 95.39it/s] 


[[149  21   7]
 [ 29  29   8]
 [  7   5  45]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.82       177
           1       0.53      0.44      0.48        66
           2       0.75      0.79      0.77        57

    accuracy                           0.74       300
   macro avg       0.69      0.69      0.69       300
weighted avg       0.73      0.74      0.74       300

Acc : 0.7433333333333333	 F1: 0.6905913440318262


Testing: 100%|██████████| 367/367 [00:03<00:00, 92.69it/s]

[[ 28  34   1]
 [ 22 141  28]
 [ 14  59  40]]
              precision    recall  f1-score   support

           0       0.44      0.44      0.44        63
           1       0.60      0.74      0.66       191
           2       0.58      0.35      0.44       113

    accuracy                           0.57       367
   macro avg       0.54      0.51      0.51       367
weighted avg       0.57      0.57      0.56       367

Acc : 0.5694822888283378	 F1: 0.5146782444049697



best en_acc_socre : 0.7633209417596035, best de_acc_score : 0.7666666666666667, best de_acc_score : 0.5776566757493188
