In [1]:
from sklearn import metrics
import processing
import time
import os
from tqdm import tqdm
from torch.optim import Adam
from torch import nn
import numpy as np
import sys
sys.path.append("D:/Experiment")
import torch
from MyKu import processing
from MyKu import MyXLM_TW
import pandas as pd

In [2]:
# 训练准备阶段，设置超参数和全局变量

batch_size = 32
num_epoch = 20  # 训练轮次
check_step = 1  # 用以训练中途对模型进行检验：每check_step个epoch进行一次测试和保存模型

learning_rate = 1e-5  # 优化器的学习率

# 获取训练、测试数据、分类类别总数
en_train_data, en_test_data, de_train_data, de_test_data, hi_train_data, hi_test_data = processing.load_hasoc2020()
categories = 2

en_train_iter, en_test_iter = MyXLM_TW.load_xlm_data(en_train_data, en_test_data, batch_size)
de_train_iter, de_test_iter = MyXLM_TW.load_xlm_data(de_train_data, de_test_data, batch_size)
hi_train_iter, hi_test_iter = MyXLM_TW.load_xlm_data(hi_train_data, hi_test_data, batch_size)
#固定写法，可以牢记，cuda代表Gpu
# torch.cuda.is_available()可以查看当前Gpu是否可用
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 加载预训练模型，因为这里是英文数据集，需要用在英文上的预训练模型：bert-base-uncased
# uncased指该预训练模型对应的词表不区分字母的大小写
# 详情可了解：https://huggingface.co/bert-base-uncased
pretrained_model_name = 'cardiffnlp/twitter-xlm-roberta-base-sentiment'
# 创建模型 BertSST2Model
model = MyXLM_TW.MyXlmModel(categories, pretrained_model_name)
# 固定写法，将模型加载到device上，
# 如果是GPU上运行，此时可以观察到GPU的显存增加
model.to(device)

# 训练过程
# Adam是最近较为常用的优化器，详情可查看：https://www.jianshu.com/p/aebcaf8af76e
optimizer = Adam(model.parameters(), learning_rate)  # 使用Adam优化器
loss = nn.CrossEntropyLoss()  # 使用crossentropy作为二分类任务的损失函数

# 记录当前训练时间，用以记录日志和存储
timestamp = time.strftime("%m_%d_%H_%M", time.localtime())

In [4]:

file_name = 'readme_tw.md'
model_save_path = 'D:/Experiment_models_save/twitter-xlm-roberta-base-sentiment/hasoc2020/'
en_temp_best = 0.88
de_temp_best = 0.85
hi_temp_best = 0.6
for epoch in range(1, num_epoch + 1):
    MyXLM_TW.train(model, en_train_iter, device, optimizer, loss, epoch)
    MyXLM_TW.train(model, de_train_iter, device, optimizer, loss, epoch)
    MyXLM_TW.train(model, hi_train_iter, device, optimizer, loss, epoch)
    en_acc_score = MyXLM_TW.test(model, en_test_iter, device, epoch, file_name)
    de_acc_score = MyXLM_TW.test(model, de_test_iter, device, epoch, file_name)
    hi_acc_score = MyXLM_TW.test(model, hi_test_iter, device, epoch, file_name)
    print('\n\n')
    if en_acc_score > en_temp_best and de_acc_score > de_temp_best and hi_acc_score > hi_temp_best:
        en_temp_best, de_temp_best, hi_temp_best = en_acc_score, de_acc_score, hi_acc_score
        MyXLM_TW.save_pretrained(model, model_save_path)
        print(
            f'best en_acc_socre : {en_acc_score}, best de_acc_score : {de_acc_score}, best hi_acc_score : {hi_acc_score}')
print(
    f'best en_acc_socre : {en_temp_best}, best de_acc_score : {de_temp_best}, best hi_acc_score : {hi_acc_score}')


Testing: 100%|██████████| 1592/1592 [00:18<00:00, 83.85it/s]


[[709  76]
 [ 80 727]]
              precision    recall  f1-score   support

           0       0.90      0.90      0.90       785
           1       0.91      0.90      0.90       807

    accuracy                           0.90      1592
   macro avg       0.90      0.90      0.90      1592
weighted avg       0.90      0.90      0.90      1592

Acc : 0.9020100502512562	 F1: 0.9019975218417293


Testing: 100%|██████████| 1027/1027 [00:12<00:00, 81.24it/s]


[[643  84]
 [ 63 237]]
              precision    recall  f1-score   support

           0       0.91      0.88      0.90       727
           1       0.74      0.79      0.76       300

    accuracy                           0.86      1027
   macro avg       0.82      0.84      0.83      1027
weighted avg       0.86      0.86      0.86      1027

Acc : 0.8568646543330087	 F1: 0.8303515141708048


Testing: 100%|██████████| 1269/1269 [00:16<00:00, 78.30it/s]


[[662 240]
 [130 237]]
              precision    recall  f1-score   support

           0       0.84      0.73      0.78       902
           1       0.50      0.65      0.56       367

    accuracy                           0.71      1269
   macro avg       0.67      0.69      0.67      1269
weighted avg       0.74      0.71      0.72      1269

Acc : 0.7084318360914106	 F1: 0.671596714358455



best en_acc_socre : 0.9020100502512562, best de_acc_score : 0.8568646543330087, best hi_acc_score : 0.7084318360914106


Testing: 100%|██████████| 1592/1592 [00:18<00:00, 84.88it/s]


[[743  42]
 [129 678]]
              precision    recall  f1-score   support

           0       0.85      0.95      0.90       785
           1       0.94      0.84      0.89       807

    accuracy                           0.89      1592
   macro avg       0.90      0.89      0.89      1592
weighted avg       0.90      0.89      0.89      1592

Acc : 0.8925879396984925	 F1: 0.8924085827465311


Testing: 100%|██████████| 1027/1027 [00:11<00:00, 88.87it/s]


[[687  40]
 [111 189]]
              precision    recall  f1-score   support

           0       0.86      0.94      0.90       727
           1       0.83      0.63      0.71       300

    accuracy                           0.85      1027
   macro avg       0.84      0.79      0.81      1027
weighted avg       0.85      0.85      0.85      1027

Acc : 0.8529698149951315	 F1: 0.8077696860764201


Testing: 100%|██████████| 1269/1269 [00:15<00:00, 79.33it/s]


[[809  93]
 [234 133]]
              precision    recall  f1-score   support

           0       0.78      0.90      0.83       902
           1       0.59      0.36      0.45       367

    accuracy                           0.74      1269
   macro avg       0.68      0.63      0.64      1269
weighted avg       0.72      0.74      0.72      1269

Acc : 0.7423167848699763	 F1: 0.6402216085695583





Testing: 100%|██████████| 1592/1592 [00:17<00:00, 89.97it/s] 


[[720  65]
 [ 84 723]]
              precision    recall  f1-score   support

           0       0.90      0.92      0.91       785
           1       0.92      0.90      0.91       807

    accuracy                           0.91      1592
   macro avg       0.91      0.91      0.91      1592
weighted avg       0.91      0.91      0.91      1592

Acc : 0.9064070351758794	 F1: 0.9064067028217112


Testing: 100%|██████████| 1027/1027 [00:12<00:00, 84.37it/s]


[[658  69]
 [ 82 218]]
              precision    recall  f1-score   support

           0       0.89      0.91      0.90       727
           1       0.76      0.73      0.74       300

    accuracy                           0.85      1027
   macro avg       0.82      0.82      0.82      1027
weighted avg       0.85      0.85      0.85      1027

Acc : 0.8529698149951315	 F1: 0.8199143217798959


Testing: 100%|██████████| 1269/1269 [00:15<00:00, 82.70it/s]


[[690 212]
 [161 206]]
              precision    recall  f1-score   support

           0       0.81      0.76      0.79       902
           1       0.49      0.56      0.52       367

    accuracy                           0.71      1269
   macro avg       0.65      0.66      0.66      1269
weighted avg       0.72      0.71      0.71      1269

Acc : 0.7060677698975572	 F1: 0.6560313348182008





Testing: 100%|██████████| 1592/1592 [00:18<00:00, 87.78it/s]


[[733  52]
 [ 92 715]]
              precision    recall  f1-score   support

           0       0.89      0.93      0.91       785
           1       0.93      0.89      0.91       807

    accuracy                           0.91      1592
   macro avg       0.91      0.91      0.91      1592
weighted avg       0.91      0.91      0.91      1592

Acc : 0.9095477386934674	 F1: 0.9095361740077501


Testing: 100%|██████████| 1027/1027 [00:12<00:00, 83.57it/s]


[[686  41]
 [106 194]]
              precision    recall  f1-score   support

           0       0.87      0.94      0.90       727
           1       0.83      0.65      0.73       300

    accuracy                           0.86      1027
   macro avg       0.85      0.80      0.81      1027
weighted avg       0.85      0.86      0.85      1027

Acc : 0.8568646543330087	 F1: 0.8142297256557129


Testing: 100%|██████████| 1269/1269 [00:15<00:00, 81.02it/s]


[[790 112]
 [231 136]]
              precision    recall  f1-score   support

           0       0.77      0.88      0.82       902
           1       0.55      0.37      0.44       367

    accuracy                           0.73      1269
   macro avg       0.66      0.62      0.63      1269
weighted avg       0.71      0.73      0.71      1269

Acc : 0.7297084318360915	 F1: 0.6319546440394201





Testing: 100%|██████████| 1592/1592 [00:18<00:00, 85.82it/s]


[[740  45]
 [118 689]]
              precision    recall  f1-score   support

           0       0.86      0.94      0.90       785
           1       0.94      0.85      0.89       807

    accuracy                           0.90      1592
   macro avg       0.90      0.90      0.90      1592
weighted avg       0.90      0.90      0.90      1592

Acc : 0.8976130653266332	 F1: 0.8975078825355085


Testing: 100%|██████████| 1027/1027 [00:11<00:00, 92.57it/s] 


[[686  41]
 [ 97 203]]
              precision    recall  f1-score   support

           0       0.88      0.94      0.91       727
           1       0.83      0.68      0.75       300

    accuracy                           0.87      1027
   macro avg       0.85      0.81      0.83      1027
weighted avg       0.86      0.87      0.86      1027

Acc : 0.8656280428432327	 F1: 0.8274664004674718


Testing: 100%|██████████| 1269/1269 [00:14<00:00, 87.49it/s]


[[814  88]
 [233 134]]
              precision    recall  f1-score   support

           0       0.78      0.90      0.84       902
           1       0.60      0.37      0.46       367

    accuracy                           0.75      1269
   macro avg       0.69      0.63      0.65      1269
weighted avg       0.73      0.75      0.73      1269

Acc : 0.7470449172576832	 F1: 0.6451543214447181





Testing: 100%|██████████| 1592/1592 [00:16<00:00, 94.13it/s]


[[728  57]
 [100 707]]
              precision    recall  f1-score   support

           0       0.88      0.93      0.90       785
           1       0.93      0.88      0.90       807

    accuracy                           0.90      1592
   macro avg       0.90      0.90      0.90      1592
weighted avg       0.90      0.90      0.90      1592

Acc : 0.9013819095477387	 F1: 0.9013647468866699


Testing: 100%|██████████| 1027/1027 [00:11<00:00, 93.29it/s] 


[[676  51]
 [ 90 210]]
              precision    recall  f1-score   support

           0       0.88      0.93      0.91       727
           1       0.80      0.70      0.75       300

    accuracy                           0.86      1027
   macro avg       0.84      0.81      0.83      1027
weighted avg       0.86      0.86      0.86      1027

Acc : 0.8627069133398247	 F1: 0.8271111891142622


Testing: 100%|██████████| 1269/1269 [00:14<00:00, 88.65it/s]


[[702 200]
 [169 198]]
              precision    recall  f1-score   support

           0       0.81      0.78      0.79       902
           1       0.50      0.54      0.52       367

    accuracy                           0.71      1269
   macro avg       0.65      0.66      0.65      1269
weighted avg       0.72      0.71      0.71      1269

Acc : 0.7092198581560284	 F1: 0.654762615706181





Testing: 100%|██████████| 1592/1592 [00:18<00:00, 86.49it/s]


[[718  67]
 [ 84 723]]
              precision    recall  f1-score   support

           0       0.90      0.91      0.90       785
           1       0.92      0.90      0.91       807

    accuracy                           0.91      1592
   macro avg       0.91      0.91      0.91      1592
weighted avg       0.91      0.91      0.91      1592

Acc : 0.9051507537688442	 F1: 0.9051498181648878


Testing: 100%|██████████| 1027/1027 [00:11<00:00, 88.37it/s]


[[673  54]
 [ 81 219]]
              precision    recall  f1-score   support

           0       0.89      0.93      0.91       727
           1       0.80      0.73      0.76       300

    accuracy                           0.87      1027
   macro avg       0.85      0.83      0.84      1027
weighted avg       0.87      0.87      0.87      1027

Acc : 0.8685491723466408	 F1: 0.8366216402529775


Testing: 100%|██████████| 1269/1269 [00:16<00:00, 79.02it/s]


[[812  90]
 [259 108]]
              precision    recall  f1-score   support

           0       0.76      0.90      0.82       902
           1       0.55      0.29      0.38       367

    accuracy                           0.72      1269
   macro avg       0.65      0.60      0.60      1269
weighted avg       0.70      0.72      0.70      1269

Acc : 0.7249802994483846	 F1: 0.6027064485599846



best en_acc_socre : 0.9051507537688442, best de_acc_score : 0.8685491723466408, best hi_acc_score : 0.7249802994483846


Testing: 100%|██████████| 1592/1592 [00:18<00:00, 85.02it/s]


[[739  46]
 [123 684]]
              precision    recall  f1-score   support

           0       0.86      0.94      0.90       785
           1       0.94      0.85      0.89       807

    accuracy                           0.89      1592
   macro avg       0.90      0.89      0.89      1592
weighted avg       0.90      0.89      0.89      1592

Acc : 0.8938442211055276	 F1: 0.8937173678686312


Testing: 100%|██████████| 1027/1027 [00:12<00:00, 84.68it/s]


[[693  34]
 [106 194]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91       727
           1       0.85      0.65      0.73       300

    accuracy                           0.86      1027
   macro avg       0.86      0.80      0.82      1027
weighted avg       0.86      0.86      0.86      1027

Acc : 0.8636806231742941	 F1: 0.821552682791215


Testing: 100%|██████████| 1269/1269 [00:15<00:00, 81.70it/s]


[[815  87]
 [243 124]]
              precision    recall  f1-score   support

           0       0.77      0.90      0.83       902
           1       0.59      0.34      0.43       367

    accuracy                           0.74      1269
   macro avg       0.68      0.62      0.63      1269
weighted avg       0.72      0.74      0.72      1269

Acc : 0.7399527186761229	 F1: 0.6303491985029306





Testing: 100%|██████████| 1592/1592 [00:17<00:00, 93.05it/s]


[[717  68]
 [ 85 722]]
              precision    recall  f1-score   support

           0       0.89      0.91      0.90       785
           1       0.91      0.89      0.90       807

    accuracy                           0.90      1592
   macro avg       0.90      0.90      0.90      1592
weighted avg       0.90      0.90      0.90      1592

Acc : 0.9038944723618091	 F1: 0.9038935243657472


Testing: 100%|██████████| 1027/1027 [00:11<00:00, 88.42it/s]


[[647  80]
 [ 70 230]]
              precision    recall  f1-score   support

           0       0.90      0.89      0.90       727
           1       0.74      0.77      0.75       300

    accuracy                           0.85      1027
   macro avg       0.82      0.83      0.83      1027
weighted avg       0.86      0.85      0.85      1027

Acc : 0.8539435248296008	 F1: 0.8251101221561237


Testing: 100%|██████████| 1269/1269 [00:14<00:00, 84.74it/s]


[[774 128]
 [226 141]]
              precision    recall  f1-score   support

           0       0.77      0.86      0.81       902
           1       0.52      0.38      0.44       367

    accuracy                           0.72      1269
   macro avg       0.65      0.62      0.63      1269
weighted avg       0.70      0.72      0.71      1269

Acc : 0.7210401891252955	 F1: 0.6286381762990298





Testing: 100%|██████████| 1592/1592 [00:16<00:00, 94.72it/s] 


[[703  82]
 [ 80 727]]
              precision    recall  f1-score   support

           0       0.90      0.90      0.90       785
           1       0.90      0.90      0.90       807

    accuracy                           0.90      1592
   macro avg       0.90      0.90      0.90      1592
weighted avg       0.90      0.90      0.90      1592

Acc : 0.8982412060301508	 F1: 0.8982180743584562


Testing: 100%|██████████| 1027/1027 [00:11<00:00, 92.47it/s] 


[[646  81]
 [ 60 240]]
              precision    recall  f1-score   support

           0       0.92      0.89      0.90       727
           1       0.75      0.80      0.77       300

    accuracy                           0.86      1027
   macro avg       0.83      0.84      0.84      1027
weighted avg       0.87      0.86      0.86      1027

Acc : 0.8627069133398247	 F1: 0.8372759421638332


Testing: 100%|██████████| 1269/1269 [00:14<00:00, 88.82it/s]


[[764 138]
 [199 168]]
              precision    recall  f1-score   support

           0       0.79      0.85      0.82       902
           1       0.55      0.46      0.50       367

    accuracy                           0.73      1269
   macro avg       0.67      0.65      0.66      1269
weighted avg       0.72      0.73      0.73      1269

Acc : 0.7344365642237982	 F1: 0.6592800035055711





Testing: 100%|██████████| 1592/1592 [00:16<00:00, 95.74it/s] 


[[716  69]
 [ 77 730]]
              precision    recall  f1-score   support

           0       0.90      0.91      0.91       785
           1       0.91      0.90      0.91       807

    accuracy                           0.91      1592
   macro avg       0.91      0.91      0.91      1592
weighted avg       0.91      0.91      0.91      1592

Acc : 0.9082914572864321	 F1: 0.9082843645581289


Testing: 100%|██████████| 1027/1027 [00:11<00:00, 91.10it/s] 


[[652  75]
 [ 67 233]]
              precision    recall  f1-score   support

           0       0.91      0.90      0.90       727
           1       0.76      0.78      0.77       300

    accuracy                           0.86      1027
   macro avg       0.83      0.84      0.83      1027
weighted avg       0.86      0.86      0.86      1027

Acc : 0.8617332035053554	 F1: 0.8341227160224212


Testing: 100%|██████████| 1269/1269 [00:14<00:00, 89.61it/s]


[[811  91]
 [255 112]]
              precision    recall  f1-score   support

           0       0.76      0.90      0.82       902
           1       0.55      0.31      0.39       367

    accuracy                           0.73      1269
   macro avg       0.66      0.60      0.61      1269
weighted avg       0.70      0.73      0.70      1269

Acc : 0.727344365642238	 F1: 0.6085847240051347





Testing: 100%|██████████| 1592/1592 [00:16<00:00, 97.57it/s] 


[[708  77]
 [ 73 734]]
              precision    recall  f1-score   support

           0       0.91      0.90      0.90       785
           1       0.91      0.91      0.91       807

    accuracy                           0.91      1592
   macro avg       0.91      0.91      0.91      1592
weighted avg       0.91      0.91      0.91      1592

Acc : 0.9057788944723618	 F1: 0.9057537568257485


Testing: 100%|██████████| 1027/1027 [00:11<00:00, 91.37it/s] 


[[644  83]
 [ 68 232]]
              precision    recall  f1-score   support

           0       0.90      0.89      0.90       727
           1       0.74      0.77      0.75       300

    accuracy                           0.85      1027
   macro avg       0.82      0.83      0.82      1027
weighted avg       0.86      0.85      0.85      1027

Acc : 0.8529698149951315	 F1: 0.824768781391775


Testing: 100%|██████████| 1269/1269 [00:14<00:00, 90.26it/s]


[[733 169]
 [189 178]]
              precision    recall  f1-score   support

           0       0.80      0.81      0.80       902
           1       0.51      0.49      0.50       367

    accuracy                           0.72      1269
   macro avg       0.65      0.65      0.65      1269
weighted avg       0.71      0.72      0.72      1269

Acc : 0.7178881008668243	 F1: 0.6511637549756746





Testing: 100%|██████████| 1592/1592 [00:16<00:00, 97.12it/s] 


[[714  71]
 [ 80 727]]
              precision    recall  f1-score   support

           0       0.90      0.91      0.90       785
           1       0.91      0.90      0.91       807

    accuracy                           0.91      1592
   macro avg       0.91      0.91      0.91      1592
weighted avg       0.91      0.91      0.91      1592

Acc : 0.9051507537688442	 F1: 0.9051444287267267


Testing: 100%|██████████| 1027/1027 [00:11<00:00, 91.22it/s]


[[613 114]
 [ 59 241]]
              precision    recall  f1-score   support

           0       0.91      0.84      0.88       727
           1       0.68      0.80      0.74       300

    accuracy                           0.83      1027
   macro avg       0.80      0.82      0.81      1027
weighted avg       0.84      0.83      0.84      1027

Acc : 0.8315481986368062	 F1: 0.8061090528130781


Testing: 100%|██████████| 1269/1269 [00:14<00:00, 90.07it/s]


[[686 216]
 [167 200]]
              precision    recall  f1-score   support

           0       0.80      0.76      0.78       902
           1       0.48      0.54      0.51       367

    accuracy                           0.70      1269
   macro avg       0.64      0.65      0.65      1269
weighted avg       0.71      0.70      0.70      1269

Acc : 0.698187549251379	 F1: 0.6463110325179291





Testing: 100%|██████████| 1592/1592 [00:17<00:00, 89.37it/s]


[[746  39]
 [127 680]]
              precision    recall  f1-score   support

           0       0.85      0.95      0.90       785
           1       0.95      0.84      0.89       807

    accuracy                           0.90      1592
   macro avg       0.90      0.90      0.90      1592
weighted avg       0.90      0.90      0.90      1592

Acc : 0.8957286432160804	 F1: 0.8955491228042439


Testing: 100%|██████████| 1027/1027 [00:12<00:00, 85.18it/s]


[[688  39]
 [104 196]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91       727
           1       0.83      0.65      0.73       300

    accuracy                           0.86      1027
   macro avg       0.85      0.80      0.82      1027
weighted avg       0.86      0.86      0.86      1027

Acc : 0.8607594936708861	 F1: 0.8192846991072582


Testing: 100%|██████████| 1269/1269 [00:15<00:00, 81.23it/s]


[[764 138]
 [222 145]]
              precision    recall  f1-score   support

           0       0.77      0.85      0.81       902
           1       0.51      0.40      0.45       367

    accuracy                           0.72      1269
   macro avg       0.64      0.62      0.63      1269
weighted avg       0.70      0.72      0.70      1269

Acc : 0.7163120567375887	 F1: 0.6277379400260756





Testing: 100%|██████████| 1592/1592 [00:18<00:00, 87.00it/s]


[[729  56]
 [ 87 720]]
              precision    recall  f1-score   support

           0       0.89      0.93      0.91       785
           1       0.93      0.89      0.91       807

    accuracy                           0.91      1592
   macro avg       0.91      0.91      0.91      1592
weighted avg       0.91      0.91      0.91      1592

Acc : 0.910175879396985	 F1: 0.9101730085784193


Testing: 100%|██████████| 1027/1027 [00:11<00:00, 89.10it/s]


[[658  69]
 [ 77 223]]
              precision    recall  f1-score   support

           0       0.90      0.91      0.90       727
           1       0.76      0.74      0.75       300

    accuracy                           0.86      1027
   macro avg       0.83      0.82      0.83      1027
weighted avg       0.86      0.86      0.86      1027

Acc : 0.857838364167478	 F1: 0.8267575886419936


Testing: 100%|██████████| 1269/1269 [00:15<00:00, 80.52it/s]


[[781 121]
 [220 147]]
              precision    recall  f1-score   support

           0       0.78      0.87      0.82       902
           1       0.55      0.40      0.46       367

    accuracy                           0.73      1269
   macro avg       0.66      0.63      0.64      1269
weighted avg       0.71      0.73      0.72      1269

Acc : 0.731284475965327	 F1: 0.6419006872695826





Testing: 100%|██████████| 1592/1592 [00:16<00:00, 94.37it/s] 


[[743  42]
 [112 695]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91       785
           1       0.94      0.86      0.90       807

    accuracy                           0.90      1592
   macro avg       0.91      0.90      0.90      1592
weighted avg       0.91      0.90      0.90      1592

Acc : 0.9032663316582915	 F1: 0.9031783141665614


Testing: 100%|██████████| 1027/1027 [00:10<00:00, 98.74it/s] 


[[671  56]
 [ 87 213]]
              precision    recall  f1-score   support

           0       0.89      0.92      0.90       727
           1       0.79      0.71      0.75       300

    accuracy                           0.86      1027
   macro avg       0.84      0.82      0.83      1027
weighted avg       0.86      0.86      0.86      1027

Acc : 0.8607594936708861	 F1: 0.8261928008852437


Testing: 100%|██████████| 1269/1269 [00:14<00:00, 87.97it/s]


[[803  99]
 [243 124]]
              precision    recall  f1-score   support

           0       0.77      0.89      0.82       902
           1       0.56      0.34      0.42       367

    accuracy                           0.73      1269
   macro avg       0.66      0.61      0.62      1269
weighted avg       0.71      0.73      0.71      1269

Acc : 0.7304964539007093	 F1: 0.6223871506630008





Testing: 100%|██████████| 1592/1592 [00:17<00:00, 93.24it/s]


[[738  47]
 [113 694]]
              precision    recall  f1-score   support

           0       0.87      0.94      0.90       785
           1       0.94      0.86      0.90       807

    accuracy                           0.90      1592
   macro avg       0.90      0.90      0.90      1592
weighted avg       0.90      0.90      0.90      1592

Acc : 0.8994974874371859	 F1: 0.89942065793547


Testing: 100%|██████████| 1027/1027 [00:10<00:00, 97.27it/s] 


[[685  42]
 [103 197]]
              precision    recall  f1-score   support

           0       0.87      0.94      0.90       727
           1       0.82      0.66      0.73       300

    accuracy                           0.86      1027
   macro avg       0.85      0.80      0.82      1027
weighted avg       0.86      0.86      0.85      1027

Acc : 0.8588120740019474	 F1: 0.8176368657273891


Testing: 100%|██████████| 1269/1269 [00:14<00:00, 87.76it/s]


[[811  91]
 [251 116]]
              precision    recall  f1-score   support

           0       0.76      0.90      0.83       902
           1       0.56      0.32      0.40       367

    accuracy                           0.73      1269
   macro avg       0.66      0.61      0.62      1269
weighted avg       0.70      0.73      0.70      1269

Acc : 0.7304964539007093	 F1: 0.6150233825585274





Testing: 100%|██████████| 1592/1592 [00:16<00:00, 94.02it/s] 


[[735  50]
 [ 97 710]]
              precision    recall  f1-score   support

           0       0.88      0.94      0.91       785
           1       0.93      0.88      0.91       807

    accuracy                           0.91      1592
   macro avg       0.91      0.91      0.91      1592
weighted avg       0.91      0.91      0.91      1592

Acc : 0.9076633165829145	 F1: 0.9076405406973371


Testing: 100%|██████████| 1027/1027 [00:10<00:00, 96.80it/s] 


[[694  33]
 [100 200]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91       727
           1       0.86      0.67      0.75       300

    accuracy                           0.87      1027
   macro avg       0.87      0.81      0.83      1027
weighted avg       0.87      0.87      0.87      1027

Acc : 0.8704965920155794	 F1: 0.8315132855470566


Testing: 100%|██████████| 1269/1269 [00:14<00:00, 88.17it/s]


[[732 170]
 [192 175]]
              precision    recall  f1-score   support

           0       0.79      0.81      0.80       902
           1       0.51      0.48      0.49       367

    accuracy                           0.71      1269
   macro avg       0.65      0.64      0.65      1269
weighted avg       0.71      0.71      0.71      1269

Acc : 0.7147360126083531	 F1: 0.646662749055466





Testing: 100%|██████████| 1592/1592 [00:16<00:00, 94.79it/s] 


[[714  71]
 [ 77 730]]
              precision    recall  f1-score   support

           0       0.90      0.91      0.91       785
           1       0.91      0.90      0.91       807

    accuracy                           0.91      1592
   macro avg       0.91      0.91      0.91      1592
weighted avg       0.91      0.91      0.91      1592

Acc : 0.907035175879397	 F1: 0.9070257847816754


Testing: 100%|██████████| 1027/1027 [00:10<00:00, 95.11it/s] 


[[664  63]
 [ 79 221]]
              precision    recall  f1-score   support

           0       0.89      0.91      0.90       727
           1       0.78      0.74      0.76       300

    accuracy                           0.86      1027
   macro avg       0.84      0.83      0.83      1027
weighted avg       0.86      0.86      0.86      1027

Acc : 0.8617332035053554	 F1: 0.8301253378063553


Testing: 100%|██████████| 1269/1269 [00:14<00:00, 88.65it/s]


[[748 154]
 [201 166]]
              precision    recall  f1-score   support

           0       0.79      0.83      0.81       902
           1       0.52      0.45      0.48       367

    accuracy                           0.72      1269
   macro avg       0.65      0.64      0.65      1269
weighted avg       0.71      0.72      0.71      1269

Acc : 0.7202521670606777	 F1: 0.6457361652735805





Testing: 100%|██████████| 1592/1592 [00:16<00:00, 94.99it/s] 


[[737  48]
 [105 702]]
              precision    recall  f1-score   support

           0       0.88      0.94      0.91       785
           1       0.94      0.87      0.90       807

    accuracy                           0.90      1592
   macro avg       0.91      0.90      0.90      1592
weighted avg       0.91      0.90      0.90      1592

Acc : 0.9038944723618091	 F1: 0.9038479985504724


Testing: 100%|██████████| 1027/1027 [00:10<00:00, 93.77it/s]


[[701  26]
 [117 183]]
              precision    recall  f1-score   support

           0       0.86      0.96      0.91       727
           1       0.88      0.61      0.72       300

    accuracy                           0.86      1027
   macro avg       0.87      0.79      0.81      1027
weighted avg       0.86      0.86      0.85      1027

Acc : 0.8607594936708861	 F1: 0.813250170077759


Testing: 100%|██████████| 1269/1269 [00:14<00:00, 88.01it/s]

[[794 108]
 [244 123]]
              precision    recall  f1-score   support

           0       0.76      0.88      0.82       902
           1       0.53      0.34      0.41       367

    accuracy                           0.72      1269
   macro avg       0.65      0.61      0.61      1269
weighted avg       0.70      0.72      0.70      1269

Acc : 0.7226162332545312	 F1: 0.6149639692445609



best en_acc_socre : 0.9051507537688442, best de_acc_score : 0.8685491723466408, best hi_acc_score : 0.7226162332545312


In [ ]:
from transformers import XLMRobertaForSequenceClassification

xlm = XLMRobertaForSequenceClassification.from_pretrained('cardiffnlp/twitter-xlm-roberta-base-sentiment', return_dict=True)
xlm.classifier.out_proj = nn.Linear(768, 2)
print(xlm.eval())