In [1]:
from sklearn import metrics
import processing
import time
import os
from tqdm import tqdm
from torch.optim import Adam
from torch import nn
import numpy as np
import sys
sys.path.append("D:/Experiment")
import torch
from MyKu import processing
from MyKu import MyXLM_TW
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
# 训练准备阶段，设置超参数和全局变量

batch_size = 32
num_epoch = 20  # 训练轮次
check_step = 1  # 用以训练中途对模型进行检验：每check_step个epoch进行一次测试和保存模型

learning_rate = 1e-5  # 优化器的学习率

# 获取训练、测试数据、分类类别总数
en_train_data, en_test_data, de_train_data, de_test_data, hi_train_data, hi_test_data = processing.load_hasoc2020_for_taskB()
categories = 3

en_train_iter, en_test_iter = MyXLM_TW.load_xlm_data(en_train_data, en_test_data, batch_size)
de_train_iter, de_test_iter = MyXLM_TW.load_xlm_data(de_train_data, de_test_data, batch_size)
hi_train_iter, hi_test_iter = MyXLM_TW.load_xlm_data(hi_train_data, hi_test_data, batch_size)
#固定写法，可以牢记，cuda代表Gpu
# torch.cuda.is_available()可以查看当前Gpu是否可用
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 加载预训练模型，因为这里是英文数据集，需要用在英文上的预训练模型：bert-base-uncased
# uncased指该预训练模型对应的词表不区分字母的大小写
# 详情可了解：https://huggingface.co/bert-base-uncased
pretrained_model_name = 'cardiffnlp/twitter-xlm-roberta-base-sentiment'
# 创建模型 BertSST2Model
model = MyXLM_TW.MyXlmModel(categories, pretrained_model_name)
# 固定写法，将模型加载到device上，
# 如果是GPU上运行，此时可以观察到GPU的显存增加
model.to(device)

# 训练过程
# Adam是最近较为常用的优化器，详情可查看：https://www.jianshu.com/p/aebcaf8af76e
optimizer = Adam(model.parameters(), learning_rate)  # 使用Adam优化器
loss = nn.CrossEntropyLoss()  # 使用crossentropy作为二分类任务的损失函数

# 记录当前训练时间，用以记录日志和存储
timestamp = time.strftime("%m_%d_%H_%M", time.localtime())

In [6]:

file_name = 'readme_tw_taskb.md'
model_save_path = 'D:/Experiment_models_save/twitter-xlm-roberta-base-sentiment/hasoc2020/'
name = 'tw_taskB.pth'
en_temp_best = 0.78
de_temp_best = 0.74
hi_temp_best = 0.58
for epoch in range(1, num_epoch + 1):
    MyXLM_TW.train(model, en_train_iter, device, optimizer, loss, epoch)
    MyXLM_TW.train(model, de_train_iter, device, optimizer, loss, epoch)
    MyXLM_TW.train(model, hi_train_iter, device, optimizer, loss, epoch)
    en_acc_score = MyXLM_TW.test(model, en_test_iter, device, epoch, file_name)
    de_acc_score = MyXLM_TW.test(model, de_test_iter, device, epoch, file_name)
    hi_acc_score = MyXLM_TW.test(model, hi_test_iter, device, epoch, file_name)
    print('\n\n')
    if en_acc_score > en_temp_best and de_acc_score > de_temp_best and hi_acc_score > hi_temp_best:
        en_temp_best, de_temp_best, hi_temp_best = en_acc_score, de_acc_score, hi_acc_score
        MyXLM_TW.save_pretrained(model, model_save_path, name)
        print(
            f'best en_acc_socre : {en_acc_score}, best de_acc_score : {de_acc_score}, best hi_acc_score : {hi_acc_score}')
print(
    f'best en_acc_socre : {en_temp_best}, best de_acc_score : {de_temp_best}, best hi_acc_score : {hi_acc_score}')


Testing: 100%|██████████| 807/807 [00:10<00:00, 79.94it/s]


[[538  21  21]
 [ 99  56  14]
 [ 32   9  17]]
              precision    recall  f1-score   support

           0       0.80      0.93      0.86       580
           1       0.65      0.33      0.44       169
           2       0.33      0.29      0.31        58

    accuracy                           0.76       807
   macro avg       0.59      0.52      0.54       807
weighted avg       0.74      0.76      0.73       807

Acc : 0.7571251548946716	 F1: 0.5365985955728337


Testing: 100%|██████████| 300/300 [00:04<00:00, 73.00it/s]


[[163   8   6]
 [ 33  27   6]
 [  6   4  47]]
              precision    recall  f1-score   support

           0       0.81      0.92      0.86       177
           1       0.69      0.41      0.51        66
           2       0.80      0.82      0.81        57

    accuracy                           0.79       300
   macro avg       0.77      0.72      0.73       300
weighted avg       0.78      0.79      0.77       300

Acc : 0.79	 F1: 0.7282629510725225


Testing: 100%|██████████| 367/367 [00:05<00:00, 70.61it/s]


[[ 32  23   8]
 [ 22 109  60]
 [  8  32  73]]
              precision    recall  f1-score   support

           0       0.52      0.51      0.51        63
           1       0.66      0.57      0.61       191
           2       0.52      0.65      0.57       113

    accuracy                           0.58       367
   macro avg       0.57      0.57      0.57       367
weighted avg       0.59      0.58      0.58       367

Acc : 0.5831062670299727	 F1: 0.5669625522161842





Testing: 100%|██████████| 807/807 [00:10<00:00, 75.11it/s]


[[536  30  14]
 [ 89  71   9]
 [ 28  16  14]]
              precision    recall  f1-score   support

           0       0.82      0.92      0.87       580
           1       0.61      0.42      0.50       169
           2       0.38      0.24      0.29        58

    accuracy                           0.77       807
   macro avg       0.60      0.53      0.55       807
weighted avg       0.74      0.77      0.75       807

Acc : 0.7695167286245354	 F1: 0.5535548357676671


Testing: 100%|██████████| 300/300 [00:03<00:00, 78.69it/s]


[[159  13   5]
 [ 29  35   2]
 [  6   9  42]]
              precision    recall  f1-score   support

           0       0.82      0.90      0.86       177
           1       0.61      0.53      0.57        66
           2       0.86      0.74      0.79        57

    accuracy                           0.79       300
   macro avg       0.76      0.72      0.74       300
weighted avg       0.78      0.79      0.78       300

Acc : 0.7866666666666666	 F1: 0.7395671261294824


Testing: 100%|██████████| 367/367 [00:05<00:00, 73.33it/s]


[[ 31  26   6]
 [ 24 143  24]
 [  6  69  38]]
              precision    recall  f1-score   support

           0       0.51      0.49      0.50        63
           1       0.60      0.75      0.67       191
           2       0.56      0.34      0.42       113

    accuracy                           0.58       367
   macro avg       0.56      0.53      0.53       367
weighted avg       0.57      0.58      0.56       367

Acc : 0.5776566757493188	 F1: 0.5288520564763659





Testing: 100%|██████████| 807/807 [00:10<00:00, 78.93it/s]


[[529  27  24]
 [ 80  70  19]
 [ 24  14  20]]
              precision    recall  f1-score   support

           0       0.84      0.91      0.87       580
           1       0.63      0.41      0.50       169
           2       0.32      0.34      0.33        58

    accuracy                           0.77       807
   macro avg       0.59      0.56      0.57       807
weighted avg       0.76      0.77      0.76       807

Acc : 0.7670384138785625	 F1: 0.5675987182020308


Testing: 100%|██████████| 300/300 [00:03<00:00, 81.85it/s]


[[154  13  10]
 [ 29  31   6]
 [  6   6  45]]
              precision    recall  f1-score   support

           0       0.81      0.87      0.84       177
           1       0.62      0.47      0.53        66
           2       0.74      0.79      0.76        57

    accuracy                           0.77       300
   macro avg       0.72      0.71      0.71       300
weighted avg       0.76      0.77      0.76       300

Acc : 0.7666666666666667	 F1: 0.7129082258907594


Testing: 100%|██████████| 367/367 [00:05<00:00, 65.93it/s]


[[ 41  16   6]
 [ 54 111  26]
 [ 21  55  37]]
              precision    recall  f1-score   support

           0       0.35      0.65      0.46        63
           1       0.61      0.58      0.60       191
           2       0.54      0.33      0.41       113

    accuracy                           0.51       367
   macro avg       0.50      0.52      0.49       367
weighted avg       0.54      0.51      0.51       367

Acc : 0.5149863760217984	 F1: 0.486622742662403





Testing: 100%|██████████| 807/807 [00:11<00:00, 72.57it/s]


[[491  73  16]
 [ 66  97   6]
 [ 16  27  15]]
              precision    recall  f1-score   support

           0       0.86      0.85      0.85       580
           1       0.49      0.57      0.53       169
           2       0.41      0.26      0.32        58

    accuracy                           0.75       807
   macro avg       0.58      0.56      0.57       807
weighted avg       0.75      0.75      0.75       807

Acc : 0.7472118959107806	 F1: 0.5658451195785995


Testing: 100%|██████████| 300/300 [00:04<00:00, 73.67it/s]


[[141  31   5]
 [ 23  40   3]
 [  4  13  40]]
              precision    recall  f1-score   support

           0       0.84      0.80      0.82       177
           1       0.48      0.61      0.53        66
           2       0.83      0.70      0.76        57

    accuracy                           0.74       300
   macro avg       0.72      0.70      0.70       300
weighted avg       0.76      0.74      0.74       300

Acc : 0.7366666666666667	 F1: 0.7042097998619737


Testing: 100%|██████████| 367/367 [00:05<00:00, 67.22it/s]


[[ 17  40   6]
 [  9 155  27]
 [  2  63  48]]
              precision    recall  f1-score   support

           0       0.61      0.27      0.37        63
           1       0.60      0.81      0.69       191
           2       0.59      0.42      0.49       113

    accuracy                           0.60       367
   macro avg       0.60      0.50      0.52       367
weighted avg       0.60      0.60      0.58       367

Acc : 0.5994550408719346	 F1: 0.5196316323448783





Testing: 100%|██████████| 807/807 [00:10<00:00, 79.47it/s]


[[524  37  19]
 [ 77  80  12]
 [ 24  21  13]]
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       580
           1       0.58      0.47      0.52       169
           2       0.30      0.22      0.25        58

    accuracy                           0.76       807
   macro avg       0.57      0.53      0.55       807
weighted avg       0.75      0.76      0.75       807

Acc : 0.7645600991325898	 F1: 0.5485947142630868


Testing: 100%|██████████| 300/300 [00:03<00:00, 83.09it/s]


[[149  22   6]
 [ 25  38   3]
 [  8  13  36]]
              precision    recall  f1-score   support

           0       0.82      0.84      0.83       177
           1       0.52      0.58      0.55        66
           2       0.80      0.63      0.71        57

    accuracy                           0.74       300
   macro avg       0.71      0.68      0.69       300
weighted avg       0.75      0.74      0.74       300

Acc : 0.7433333333333333	 F1: 0.6942428361096148


Testing: 100%|██████████| 367/367 [00:04<00:00, 75.15it/s]


[[ 21  40   2]
 [  9 170  12]
 [  4  80  29]]
              precision    recall  f1-score   support

           0       0.62      0.33      0.43        63
           1       0.59      0.89      0.71       191
           2       0.67      0.26      0.37       113

    accuracy                           0.60       367
   macro avg       0.63      0.49      0.50       367
weighted avg       0.62      0.60      0.56       367

Acc : 0.5994550408719346	 F1: 0.5038817564590761





Testing: 100%|██████████| 807/807 [00:09<00:00, 83.74it/s]


[[540  21  19]
 [ 92  62  15]
 [ 25  14  19]]
              precision    recall  f1-score   support

           0       0.82      0.93      0.87       580
           1       0.64      0.37      0.47       169
           2       0.36      0.33      0.34        58

    accuracy                           0.77       807
   macro avg       0.61      0.54      0.56       807
weighted avg       0.75      0.77      0.75       807

Acc : 0.7695167286245354	 F1: 0.5605292627374915


Testing: 100%|██████████| 300/300 [00:04<00:00, 74.42it/s]


[[156  13   8]
 [ 32  31   3]
 [  7   6  44]]
              precision    recall  f1-score   support

           0       0.80      0.88      0.84       177
           1       0.62      0.47      0.53        66
           2       0.80      0.77      0.79        57

    accuracy                           0.77       300
   macro avg       0.74      0.71      0.72       300
weighted avg       0.76      0.77      0.76       300

Acc : 0.77	 F1: 0.7196355739181101


Testing: 100%|██████████| 367/367 [00:05<00:00, 71.05it/s]


[[ 31  27   5]
 [ 18 132  41]
 [  5  48  60]]
              precision    recall  f1-score   support

           0       0.57      0.49      0.53        63
           1       0.64      0.69      0.66       191
           2       0.57      0.53      0.55       113

    accuracy                           0.61       367
   macro avg       0.59      0.57      0.58       367
weighted avg       0.60      0.61      0.60       367

Acc : 0.6076294277929155	 F1: 0.5803921061028516





Testing: 100%|██████████| 807/807 [00:09<00:00, 82.15it/s]


[[527  36  17]
 [ 72  83  14]
 [ 21  19  18]]
              precision    recall  f1-score   support

           0       0.85      0.91      0.88       580
           1       0.60      0.49      0.54       169
           2       0.37      0.31      0.34        58

    accuracy                           0.78       807
   macro avg       0.61      0.57      0.59       807
weighted avg       0.76      0.78      0.77       807

Acc : 0.7781908302354399	 F1: 0.5851661812806749


Testing: 100%|██████████| 300/300 [00:03<00:00, 97.04it/s] 


[[156  16   5]
 [ 29  32   5]
 [  9   5  43]]
              precision    recall  f1-score   support

           0       0.80      0.88      0.84       177
           1       0.60      0.48      0.54        66
           2       0.81      0.75      0.78        57

    accuracy                           0.77       300
   macro avg       0.74      0.71      0.72       300
weighted avg       0.76      0.77      0.76       300

Acc : 0.77	 F1: 0.7202012194243048


Testing: 100%|██████████| 367/367 [00:03<00:00, 98.35it/s] 


[[ 29  26   8]
 [ 18 128  45]
 [  3  52  58]]
              precision    recall  f1-score   support

           0       0.58      0.46      0.51        63
           1       0.62      0.67      0.64       191
           2       0.52      0.51      0.52       113

    accuracy                           0.59       367
   macro avg       0.57      0.55      0.56       367
weighted avg       0.58      0.59      0.58       367

Acc : 0.5858310626702997	 F1: 0.5586559170602103





Testing: 100%|██████████| 807/807 [00:08<00:00, 90.47it/s] 


[[497  59  24]
 [ 64  88  17]
 [ 18  21  19]]
              precision    recall  f1-score   support

           0       0.86      0.86      0.86       580
           1       0.52      0.52      0.52       169
           2       0.32      0.33      0.32        58

    accuracy                           0.75       807
   macro avg       0.57      0.57      0.57       807
weighted avg       0.75      0.75      0.75       807

Acc : 0.748451053283767	 F1: 0.5673083280648799


Testing: 100%|██████████| 300/300 [00:03<00:00, 97.55it/s] 


[[150  15  12]
 [ 27  28  11]
 [  4   6  47]]
              precision    recall  f1-score   support

           0       0.83      0.85      0.84       177
           1       0.57      0.42      0.49        66
           2       0.67      0.82      0.74        57

    accuracy                           0.75       300
   macro avg       0.69      0.70      0.69       300
weighted avg       0.74      0.75      0.74       300

Acc : 0.75	 F1: 0.6883676096232446


Testing: 100%|██████████| 367/367 [00:03<00:00, 95.73it/s]


[[ 29  28   6]
 [ 28 111  52]
 [ 11  44  58]]
              precision    recall  f1-score   support

           0       0.43      0.46      0.44        63
           1       0.61      0.58      0.59       191
           2       0.50      0.51      0.51       113

    accuracy                           0.54       367
   macro avg       0.51      0.52      0.51       367
weighted avg       0.54      0.54      0.54       367

Acc : 0.5395095367847411	 F1: 0.5142937325480665





Testing: 100%|██████████| 807/807 [00:09<00:00, 89.16it/s]


[[550  21   9]
 [100  66   3]
 [ 28  18  12]]
              precision    recall  f1-score   support

           0       0.81      0.95      0.87       580
           1       0.63      0.39      0.48       169
           2       0.50      0.21      0.29        58

    accuracy                           0.78       807
   macro avg       0.65      0.52      0.55       807
weighted avg       0.75      0.78      0.75       807

Acc : 0.7781908302354399	 F1: 0.5496128557423575


Testing: 100%|██████████| 300/300 [00:02<00:00, 100.19it/s]


[[163  10   4]
 [ 32  27   7]
 [  8   5  44]]
              precision    recall  f1-score   support

           0       0.80      0.92      0.86       177
           1       0.64      0.41      0.50        66
           2       0.80      0.77      0.79        57

    accuracy                           0.78       300
   macro avg       0.75      0.70      0.71       300
weighted avg       0.77      0.78      0.77       300

Acc : 0.78	 F1: 0.7145363408521304


Testing: 100%|██████████| 367/367 [00:03<00:00, 98.73it/s] 


[[ 28  33   2]
 [ 18 141  32]
 [  5  67  41]]
              precision    recall  f1-score   support

           0       0.55      0.44      0.49        63
           1       0.59      0.74      0.65       191
           2       0.55      0.36      0.44       113

    accuracy                           0.57       367
   macro avg       0.56      0.52      0.53       367
weighted avg       0.57      0.57      0.56       367

Acc : 0.5722070844686649	 F1: 0.5267253535730579





Testing: 100%|██████████| 807/807 [00:08<00:00, 92.30it/s] 


[[549  18  13]
 [106  54   9]
 [ 29  12  17]]
              precision    recall  f1-score   support

           0       0.80      0.95      0.87       580
           1       0.64      0.32      0.43       169
           2       0.44      0.29      0.35        58

    accuracy                           0.77       807
   macro avg       0.63      0.52      0.55       807
weighted avg       0.74      0.77      0.74       807

Acc : 0.7682775712515489	 F1: 0.5486879401164021


Testing: 100%|██████████| 300/300 [00:03<00:00, 99.26it/s] 


[[158   9  10]
 [ 35  21  10]
 [  7   4  46]]
              precision    recall  f1-score   support

           0       0.79      0.89      0.84       177
           1       0.62      0.32      0.42        66
           2       0.70      0.81      0.75        57

    accuracy                           0.75       300
   macro avg       0.70      0.67      0.67       300
weighted avg       0.73      0.75      0.73       300

Acc : 0.75	 F1: 0.6687212553823151


Testing: 100%|██████████| 367/367 [00:03<00:00, 97.19it/s] 


[[ 42  16   5]
 [ 51 105  35]
 [ 17  51  45]]
              precision    recall  f1-score   support

           0       0.38      0.67      0.49        63
           1       0.61      0.55      0.58       191
           2       0.53      0.40      0.45       113

    accuracy                           0.52       367
   macro avg       0.51      0.54      0.51       367
weighted avg       0.55      0.52      0.52       367

Acc : 0.5231607629427792	 F1: 0.5062023280625488





Testing: 100%|██████████| 807/807 [00:08<00:00, 93.53it/s] 


[[536  24  20]
 [ 83  67  19]
 [ 20  15  23]]
              precision    recall  f1-score   support

           0       0.84      0.92      0.88       580
           1       0.63      0.40      0.49       169
           2       0.37      0.40      0.38        58

    accuracy                           0.78       807
   macro avg       0.61      0.57      0.58       807
weighted avg       0.76      0.78      0.76       807

Acc : 0.7757125154894672	 F1: 0.5833384708446234


Testing: 100%|██████████| 300/300 [00:03<00:00, 99.46it/s] 


[[156   9  12]
 [ 30  25  11]
 [  5   3  49]]
              precision    recall  f1-score   support

           0       0.82      0.88      0.85       177
           1       0.68      0.38      0.49        66
           2       0.68      0.86      0.76        57

    accuracy                           0.77       300
   macro avg       0.72      0.71      0.70       300
weighted avg       0.76      0.77      0.75       300

Acc : 0.7666666666666667	 F1: 0.6976509675470085


Testing: 100%|██████████| 367/367 [00:03<00:00, 95.79it/s] 


[[ 39  22   2]
 [ 28 145  18]
 [  7  65  41]]
              precision    recall  f1-score   support

           0       0.53      0.62      0.57        63
           1       0.62      0.76      0.69       191
           2       0.67      0.36      0.47       113

    accuracy                           0.61       367
   macro avg       0.61      0.58      0.58       367
weighted avg       0.62      0.61      0.60       367

Acc : 0.6130790190735694	 F1: 0.5753955432423389





Testing: 100%|██████████| 807/807 [00:08<00:00, 94.59it/s] 


[[531  25  24]
 [ 84  69  16]
 [ 24  14  20]]
              precision    recall  f1-score   support

           0       0.83      0.92      0.87       580
           1       0.64      0.41      0.50       169
           2       0.33      0.34      0.34        58

    accuracy                           0.77       807
   macro avg       0.60      0.56      0.57       807
weighted avg       0.75      0.77      0.75       807

Acc : 0.7682775712515489	 F1: 0.5694613010588516


Testing: 100%|██████████| 300/300 [00:02<00:00, 100.29it/s]


[[154  10  13]
 [ 32  21  13]
 [  5   4  48]]
              precision    recall  f1-score   support

           0       0.81      0.87      0.84       177
           1       0.60      0.32      0.42        66
           2       0.65      0.84      0.73        57

    accuracy                           0.74       300
   macro avg       0.68      0.68      0.66       300
weighted avg       0.73      0.74      0.72       300

Acc : 0.7433333333333333	 F1: 0.6618741777928208


Testing: 100%|██████████| 367/367 [00:03<00:00, 98.53it/s] 


[[ 40  19   4]
 [ 34 120  37]
 [  9  56  48]]
              precision    recall  f1-score   support

           0       0.48      0.63      0.55        63
           1       0.62      0.63      0.62       191
           2       0.54      0.42      0.48       113

    accuracy                           0.57       367
   macro avg       0.55      0.56      0.55       367
weighted avg       0.57      0.57      0.56       367

Acc : 0.5667574931880109	 F1: 0.5483181294210051





Testing: 100%|██████████| 807/807 [00:08<00:00, 96.38it/s] 


[[530  35  15]
 [ 84  75  10]
 [ 28  21   9]]
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       580
           1       0.57      0.44      0.50       169
           2       0.26      0.16      0.20        58

    accuracy                           0.76       807
   macro avg       0.55      0.50      0.52       807
weighted avg       0.73      0.76      0.74       807

Acc : 0.7608426270136307	 F1: 0.5210275386038569


Testing: 100%|██████████| 300/300 [00:03<00:00, 98.93it/s] 


[[155  17   5]
 [ 26  36   4]
 [  5  10  42]]
              precision    recall  f1-score   support

           0       0.83      0.88      0.85       177
           1       0.57      0.55      0.56        66
           2       0.82      0.74      0.78        57

    accuracy                           0.78       300
   macro avg       0.74      0.72      0.73       300
weighted avg       0.77      0.78      0.77       300

Acc : 0.7766666666666666	 F1: 0.7299706010065418


Testing: 100%|██████████| 367/367 [00:03<00:00, 99.31it/s] 


[[ 31  27   5]
 [ 18 136  37]
 [  5  55  53]]
              precision    recall  f1-score   support

           0       0.57      0.49      0.53        63
           1       0.62      0.71      0.67       191
           2       0.56      0.47      0.51       113

    accuracy                           0.60       367
   macro avg       0.59      0.56      0.57       367
weighted avg       0.59      0.60      0.59       367

Acc : 0.5994550408719346	 F1: 0.5681888631155134





Testing: 100%|██████████| 807/807 [00:08<00:00, 96.33it/s] 


[[532  33  15]
 [ 81  78  10]
 [ 22  19  17]]
              precision    recall  f1-score   support

           0       0.84      0.92      0.88       580
           1       0.60      0.46      0.52       169
           2       0.40      0.29      0.34        58

    accuracy                           0.78       807
   macro avg       0.61      0.56      0.58       807
weighted avg       0.76      0.78      0.76       807

Acc : 0.7769516728624535	 F1: 0.5791530983479454


Testing: 100%|██████████| 300/300 [00:03<00:00, 97.50it/s] 


[[150  17  10]
 [ 26  35   5]
 [  5   9  43]]
              precision    recall  f1-score   support

           0       0.83      0.85      0.84       177
           1       0.57      0.53      0.55        66
           2       0.74      0.75      0.75        57

    accuracy                           0.76       300
   macro avg       0.71      0.71      0.71       300
weighted avg       0.76      0.76      0.76       300

Acc : 0.76	 F1: 0.7123320053781231


Testing: 100%|██████████| 367/367 [00:03<00:00, 98.67it/s] 


[[ 29  28   6]
 [ 11 143  37]
 [  3  58  52]]
              precision    recall  f1-score   support

           0       0.67      0.46      0.55        63
           1       0.62      0.75      0.68       191
           2       0.55      0.46      0.50       113

    accuracy                           0.61       367
   macro avg       0.62      0.56      0.58       367
weighted avg       0.61      0.61      0.60       367

Acc : 0.6103542234332425	 F1: 0.5760407307577119





Testing: 100%|██████████| 807/807 [00:08<00:00, 96.91it/s] 


[[536  32  12]
 [ 80  82   7]
 [ 26  21  11]]
              precision    recall  f1-score   support

           0       0.83      0.92      0.88       580
           1       0.61      0.49      0.54       169
           2       0.37      0.19      0.25        58

    accuracy                           0.78       807
   macro avg       0.60      0.53      0.56       807
weighted avg       0.75      0.78      0.76       807

Acc : 0.7794299876084263	 F1: 0.555574697791943


Testing: 100%|██████████| 300/300 [00:02<00:00, 102.69it/s]


[[159  16   2]
 [ 28  34   4]
 [  7  14  36]]
              precision    recall  f1-score   support

           0       0.82      0.90      0.86       177
           1       0.53      0.52      0.52        66
           2       0.86      0.63      0.73        57

    accuracy                           0.76       300
   macro avg       0.74      0.68      0.70       300
weighted avg       0.76      0.76      0.76       300

Acc : 0.7633333333333333	 F1: 0.7024975024975024


Testing: 100%|██████████| 367/367 [00:03<00:00, 99.01it/s] 


[[ 27  34   2]
 [ 11 159  21]
 [  6  66  41]]
              precision    recall  f1-score   support

           0       0.61      0.43      0.50        63
           1       0.61      0.83      0.71       191
           2       0.64      0.36      0.46       113

    accuracy                           0.62       367
   macro avg       0.62      0.54      0.56       367
weighted avg       0.62      0.62      0.60       367

Acc : 0.6185286103542235	 F1: 0.5582054666737069





Testing: 100%|██████████| 807/807 [00:08<00:00, 98.47it/s] 


[[543  21  16]
 [ 92  63  14]
 [ 28  11  19]]
              precision    recall  f1-score   support

           0       0.82      0.94      0.87       580
           1       0.66      0.37      0.48       169
           2       0.39      0.33      0.36        58

    accuracy                           0.77       807
   macro avg       0.62      0.55      0.57       807
weighted avg       0.76      0.77      0.75       807

Acc : 0.7744733581164808	 F1: 0.5687018643970095


Testing: 100%|██████████| 300/300 [00:02<00:00, 100.58it/s]


[[157  11   9]
 [ 28  28  10]
 [  6   6  45]]
              precision    recall  f1-score   support

           0       0.82      0.89      0.85       177
           1       0.62      0.42      0.50        66
           2       0.70      0.79      0.74        57

    accuracy                           0.77       300
   macro avg       0.72      0.70      0.70       300
weighted avg       0.76      0.77      0.76       300

Acc : 0.7666666666666667	 F1: 0.7005223423207614


Testing: 100%|██████████| 367/367 [00:03<00:00, 99.70it/s] 


[[ 25  32   6]
 [ 10 154  27]
 [  2  68  43]]
              precision    recall  f1-score   support

           0       0.68      0.40      0.50        63
           1       0.61      0.81      0.69       191
           2       0.57      0.38      0.46       113

    accuracy                           0.60       367
   macro avg       0.62      0.53      0.55       367
weighted avg       0.61      0.60      0.59       367

Acc : 0.6049046321525886	 F1: 0.5490537621623764





Testing: 100%|██████████| 807/807 [00:08<00:00, 99.27it/s] 


[[546  18  16]
 [ 98  53  18]
 [ 28  13  17]]
              precision    recall  f1-score   support

           0       0.81      0.94      0.87       580
           1       0.63      0.31      0.42       169
           2       0.33      0.29      0.31        58

    accuracy                           0.76       807
   macro avg       0.59      0.52      0.53       807
weighted avg       0.74      0.76      0.74       807

Acc : 0.7633209417596035	 F1: 0.5343678034546159


Testing: 100%|██████████| 300/300 [00:02<00:00, 100.93it/s]


[[163   9   5]
 [ 32  18  16]
 [  6   2  49]]
              precision    recall  f1-score   support

           0       0.81      0.92      0.86       177
           1       0.62      0.27      0.38        66
           2       0.70      0.86      0.77        57

    accuracy                           0.77       300
   macro avg       0.71      0.68      0.67       300
weighted avg       0.75      0.77      0.74       300

Acc : 0.7666666666666667	 F1: 0.6710115913873338


Testing: 100%|██████████| 367/367 [00:03<00:00, 100.56it/s]


[[ 29  30   4]
 [ 19 145  27]
 [  8  64  41]]
              precision    recall  f1-score   support

           0       0.52      0.46      0.49        63
           1       0.61      0.76      0.67       191
           2       0.57      0.36      0.44       113

    accuracy                           0.59       367
   macro avg       0.56      0.53      0.54       367
weighted avg       0.58      0.59      0.57       367

Acc : 0.5858310626702997	 F1: 0.5350189352925331





Testing: 100%|██████████| 807/807 [00:08<00:00, 99.46it/s] 


[[522  42  16]
 [ 73  84  12]
 [ 23  21  14]]
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       580
           1       0.57      0.50      0.53       169
           2       0.33      0.24      0.28        58

    accuracy                           0.77       807
   macro avg       0.58      0.55      0.56       807
weighted avg       0.75      0.77      0.76       807

Acc : 0.7682775712515489	 F1: 0.5610326634404739


Testing: 100%|██████████| 300/300 [00:02<00:00, 101.91it/s]


[[148  16  13]
 [ 25  36   5]
 [  3   5  49]]
              precision    recall  f1-score   support

           0       0.84      0.84      0.84       177
           1       0.63      0.55      0.59        66
           2       0.73      0.86      0.79        57

    accuracy                           0.78       300
   macro avg       0.73      0.75      0.74       300
weighted avg       0.77      0.78      0.77       300

Acc : 0.7766666666666666	 F1: 0.738071782161667


Testing: 100%|██████████| 367/367 [00:03<00:00, 100.76it/s]


[[ 23  36   4]
 [ 10 149  32]
 [  2  56  55]]
              precision    recall  f1-score   support

           0       0.66      0.37      0.47        63
           1       0.62      0.78      0.69       191
           2       0.60      0.49      0.54       113

    accuracy                           0.62       367
   macro avg       0.63      0.54      0.57       367
weighted avg       0.62      0.62      0.61       367

Acc : 0.6185286103542235	 F1: 0.5661394187304553





Testing: 100%|██████████| 807/807 [00:08<00:00, 99.50it/s] 


[[497  64  19]
 [ 67  91  11]
 [ 21  23  14]]
              precision    recall  f1-score   support

           0       0.85      0.86      0.85       580
           1       0.51      0.54      0.52       169
           2       0.32      0.24      0.27        58

    accuracy                           0.75       807
   macro avg       0.56      0.55      0.55       807
weighted avg       0.74      0.75      0.74       807

Acc : 0.7459727385377943	 F1: 0.5507414550917232


Testing: 100%|██████████| 300/300 [00:02<00:00, 102.55it/s]


[[147  23   7]
 [ 24  36   6]
 [  6   7  44]]
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       177
           1       0.55      0.55      0.55        66
           2       0.77      0.77      0.77        57

    accuracy                           0.76       300
   macro avg       0.72      0.72      0.72       300
weighted avg       0.76      0.76      0.76       300

Acc : 0.7566666666666667	 F1: 0.71596428153074


Testing: 100%|██████████| 367/367 [00:03<00:00, 100.29it/s]


[[ 19  37   7]
 [  6 133  52]
 [  1  50  62]]
              precision    recall  f1-score   support

           0       0.73      0.30      0.43        63
           1       0.60      0.70      0.65       191
           2       0.51      0.55      0.53       113

    accuracy                           0.58       367
   macro avg       0.62      0.52      0.53       367
weighted avg       0.60      0.58      0.57       367

Acc : 0.5831062670299727	 F1: 0.5346942561737936





Testing: 100%|██████████| 807/807 [00:08<00:00, 99.10it/s] 


[[541  23  16]
 [109  51   9]
 [ 27  12  19]]
              precision    recall  f1-score   support

           0       0.80      0.93      0.86       580
           1       0.59      0.30      0.40       169
           2       0.43      0.33      0.37        58

    accuracy                           0.76       807
   macro avg       0.61      0.52      0.54       807
weighted avg       0.73      0.76      0.73       807

Acc : 0.7571251548946716	 F1: 0.5444428845523891


Testing: 100%|██████████| 300/300 [00:02<00:00, 102.92it/s]


[[154  15   8]
 [ 30  27   9]
 [  6   6  45]]
              precision    recall  f1-score   support

           0       0.81      0.87      0.84       177
           1       0.56      0.41      0.47        66
           2       0.73      0.79      0.76        57

    accuracy                           0.75       300
   macro avg       0.70      0.69      0.69       300
weighted avg       0.74      0.75      0.74       300

Acc : 0.7533333333333333	 F1: 0.6897412629184757


Testing: 100%|██████████| 367/367 [00:03<00:00, 100.45it/s]

[[ 28  33   2]
 [ 19 140  32]
 [  6  49  58]]
              precision    recall  f1-score   support

           0       0.53      0.44      0.48        63
           1       0.63      0.73      0.68       191
           2       0.63      0.51      0.57       113

    accuracy                           0.62       367
   macro avg       0.60      0.56      0.58       367
weighted avg       0.61      0.62      0.61       367

Acc : 0.6158038147138964	 F1: 0.5755261269737186



best en_acc_socre : 0.78, best de_acc_score : 0.74, best hi_acc_score : 0.6158038147138964


In [ ]:
from transformers import XLMRobertaForSequenceClassification

xlm = XLMRobertaForSequenceClassification.from_pretrained('cardiffnlp/twitter-xlm-roberta-base-sentiment', return_dict=True)
xlm.classifier.out_proj = nn.Linear(768, 2)
print(xlm.eval())